/* Copyright (C) 2012-13 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */


/*
 * 
 */

package es.seap.minhap.portafirmas.ws.afirma5.validarcertificado.client;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.0
 * Fri Apr 26 09:49:46 CEST 2013
 * Generated source version: 2.3.0
 * 
 */


@WebServiceClient(name = "ValidacionService", 
                  //wsdlLocation = "https://des-afirma.redsara.es/afirmaws/services/ValidarCertificado?wsdl",
				  wsdlLocation = "file://afirma5/validarcertificado/ValidarCertificado.wsdl",
                  targetNamespace = "http://afirmaws/services/ValidarCertificado") 
public class ValidacionService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://afirmaws/services/ValidarCertificado", "ValidacionService");
    public final static QName ValidarCertificado = new QName("http://afirmaws/services/ValidarCertificado", "ValidarCertificado");
    static {
        URL url = null;
        try {
            //url = new URL("https://des-afirma.redsara.es/afirmaws/services/ValidarCertificado?wsdl");
        	File f = new File ("afirma5/validarcertificado/ValidarCertificado.wsdl");
        	url = f.toURI().toURL();
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from https://des-afirma.redsara.es/afirmaws/services/ValidarCertificado?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ValidacionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ValidacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidacionService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    /*public ValidacionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public ValidacionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ValidacionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }*/

    /**
     * 
     * @return
     *     returns Validacion
     */
    @WebEndpoint(name = "ValidarCertificado")
    public Validacion getValidarCertificado() {
        return super.getPort(ValidarCertificado, Validacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Validacion
     */
    @WebEndpoint(name = "ValidarCertificado")
    public Validacion getValidarCertificado(WebServiceFeature... features) {
        return super.getPort(ValidarCertificado, Validacion.class, features);
    }

}
