insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD01 - Resolución', 'TD01-ENI', 'TD01 - Resolución.','SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD02 - Acuerdo', 'TD02-ENI', 'TD02 - Acuerdo.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD03 - Contrato', 'TD03-ENI', 'TD03 - Contrato.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD04 - Convenio', 'TD04-ENI', 'TD04 - Convenio.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD05 - Declaración', 'TD05-ENI', 'TD05 - Declaración.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD06 - Comunicación', 'TD06-ENI', 'TD06 - Comunicación.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD07 - Notificación', 'TD07-ENI', 'TD07 - Notificación.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD08 - Publicación', 'TD08-ENI', 'TD08 - Publicación.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD09 - Acuse de recibo', 'TD09-ENI', 'TD09 - Acuse de recibo.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD10 - Acta', 'TD10-ENI', 'TD10 - Acta.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD11 - Certificado', 'TD11-ENI', 'TD11 - Certificado.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD12 - Diligencia', 'TD12-ENI', 'TD12 - Diligencia.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD13 - Informe', 'TD13-ENI', 'TD13 - Informe.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD14 - Solicitud', 'TD14-ENI', 'TD14 - Solicitud.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD15 - Denuncia', 'TD15-ENI', 'TD15 - Denuncia.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD16 - Alegación', 'TD16-ENI', 'TD16 - Alegación.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD17 - Recursos', 'TD17-ENI', 'TD17 - Recursos.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD18 - Comunicación ciudadano', 'TD18-ENI', 'TD18 - Comunicación ciudadano.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD19 - Factura', 'TD19-ENI', 'TD19 - Factura.', 'SYSSUPERUSER', NOW());
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (nextval('SPAC_SQ_ID_CTTPDOC'),'TD20 - Otros incautados', 'TD20-ENI', 'TD20 - Otros incautados.', 'SYSSUPERUSER', NOW());
