insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD01 - Resolución', 'TD01-ENI', 'TD01 - Resolución.','SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD02 - Acuerdo', 'TD02-ENI', 'TD02 - Acuerdo.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD03 - Contrato', 'TD03-ENI', 'TD03 - Contrato.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD04 - Convenio', 'TD04-ENI', 'TD04 - Convenio.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD05 - Declaración', 'TD05-ENI', 'TD05 - Declaración.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD06 - Comunicación', 'TD06-ENI', 'TD06 - Comunicación.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD07 - Notificación', 'TD07-ENI', 'TD07 - Notificación.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD08 - Publicación', 'TD08-ENI', 'TD08 - Publicación.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD09 - Acuse de recibo', 'TD09-ENI', 'TD09 - Acuse de recibo.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD10 - Acta', 'TD10-ENI', 'TD10 - Acta.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD11 - Certificado', 'TD11-ENI', 'TD11 - Certificado.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD12 - Diligencia', 'TD12-ENI', 'TD12 - Diligencia.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD13 - Informe', 'TD13-ENI', 'TD13 - Informe.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD14 - Solicitud', 'TD14-ENI', 'TD14 - Solicitud.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD15 - Denuncia', 'TD15-ENI', 'TD15 - Denuncia.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD16 - Alegación', 'TD16-ENI', 'TD16 - Alegación.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD17 - Recursos', 'TD17-ENI', 'TD17 - Recursos.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD18 - Comunicación ciudadano', 'TD18-ENI', 'TD18 - Comunicación ciudadano.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD19 - Factura', 'TD19-ENI', 'TD19 - Factura.', 'SYSSUPERUSER', sysdate);
insert into spac_ct_tpdoc (id, nombre, cod_tpdoc, tipo, autor, fecha) values (SPAC_SQ_ID_CTTPDOC.nextval,'TD20 - Otros incautados', 'TD20-ENI', 'TD20 - Otros incautados.', 'SYSSUPERUSER', sysdate);
