/* Copyright (C) 2012-13 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */

package es.map.directorio.manager.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-07-31T09:50:39.494+02:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "SD01UN_DescargaUnidadesService",
                  wsdlLocation = "http://se-dir3ws.redsara.es/directorio/services/SD01UN_DescargaUnidades?wsdl",
                  targetNamespace = "http://impl.manager.directorio.map.es")
public class SD01UNDescargaUnidadesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.manager.directorio.map.es", "SD01UN_DescargaUnidadesService");
    public final static QName SD01UNDescargaUnidades = new QName("http://impl.manager.directorio.map.es", "SD01UN_DescargaUnidades");
    static {
        URL url = null;
        try {
            url = new URL("http://se-dir3ws.redsara.es/directorio/services/SD01UN_DescargaUnidades?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SD01UNDescargaUnidadesService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://se-dir3ws.redsara.es/directorio/services/SD01UN_DescargaUnidades?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SD01UNDescargaUnidadesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SD01UNDescargaUnidadesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SD01UNDescargaUnidadesService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *     returns SD01UNDescargaUnidades
     */
    @WebEndpoint(name = "SD01UN_DescargaUnidades")
    public SD01UNDescargaUnidades getSD01UNDescargaUnidades() {
        return super.getPort(SD01UNDescargaUnidades, SD01UNDescargaUnidades.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SD01UNDescargaUnidades
     */
    @WebEndpoint(name = "SD01UN_DescargaUnidades")
    public SD01UNDescargaUnidades getSD01UNDescargaUnidades(WebServiceFeature... features) {
        return super.getPort(SD01UNDescargaUnidades, SD01UNDescargaUnidades.class, features);
    }

}
