/* Copyright (C) 2012-13 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */


package es.seap.minhap.portafirmas.ws.sim.peticion;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import es.seap.minhap.portafirmas.ws.sim.respuesta.Respuesta;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-09-26T12:44:14.594+02:00
 * Generated source version: 3.0.3
 * 
 */
public final class EnvioMensajesServiceWSBindingPortType_EnvioMensajesServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://misim.redsara.es/misim-bus-webapp/", "EnvioMensajesService");

    private EnvioMensajesServiceWSBindingPortType_EnvioMensajesServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EnvioMensajesService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EnvioMensajesService ss = new EnvioMensajesService(wsdlURL, SERVICE_NAME);
        EnvioMensajesServiceWSBindingPortType port = ss.getEnvioMensajesServicePort();  
        
        {
        System.out.println("Invoking enviarMensaje...");
        Peticion _enviarMensaje_peticion = null;
        Respuesta _enviarMensaje__return = port.enviarMensaje(_enviarMensaje_peticion);
        System.out.println("enviarMensaje.result=" + _enviarMensaje__return);


        }

        System.exit(0);
    }

}
