ls -l $HOME/tomcat7/webapps/SIGEM_ConsultaWeb/img/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_ConsultaWeb/WEB-INF/classes/SIGEM_ConsultaWeb/skin/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_GestionCSVWeb/img/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_GestionCSVWeb/WEB-INF/classes/SIGEM_GestionCSVWeb/skin/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_GestionCSVWeb/WEB-INF/classes/SIGEM_GestionCSVWeb/skinDefecto/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_GestionCSVWeb/WEB-INF/classes/SIGEM_GestionCSVWeb/skinEntidad_000/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_ConsultaRegistroTelematicoWeb/img/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_ConsultaRegistroTelematicoWeb/WEB-INF/classes/SIGEM_ConsultaRegistroTelematicoWeb/skin/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_TramitacionWS/img/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/img/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/tramites/000/BOP_1/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/tramites/000/BOP_1_BDNS/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/tramites/000/DPCR_RH_CERT/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/tramites/000/DPCR_SRS/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/WEB-INF/classes/SIGEM_RegistroTelematicoWeb/skin/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/WEB-INF/classes/SIGEM_RegistroTelematicoWeb/skinDefecto/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/WEB-INF/classes/SIGEM_RegistroTelematicoWeb/skinEntidad_000/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/img/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skin/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinDefecto/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_001/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_002/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_003/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_004/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_005/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_007/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_008/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_009/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_010/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_013/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_026/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_030/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_037/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_040/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_044/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_047/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_057/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_060/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_061/logos/logo.gif
ls -l $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_062/logos/logo.gif