/* Copyright (C) 2012-13 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */

package es.seap.minhap.portafirmas.ws.advice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import es.seap.minhap.portafirmas.ws.bean.Authentication;
import es.seap.minhap.portafirmas.ws.bean.Request;
import es.seap.minhap.portafirmas.ws.bean.Signature;
import es.seap.minhap.portafirmas.ws.exception.PfirmaException;


/**
 * This class was generated by Apache CXF 2.2.2
 * Tue Feb 02 13:10:47 CET 2010
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "urn:juntadeandalucia:cice:pfirma:advice:v2.0", name = "AdviceService")
public interface AdviceService {  
    /**
     * 
     * @param authentication
     * @param request
     * @param signature
     * @return
     * @throws PfirmaException
     */
    @ResponseWrapper(localName = "updateRequestStatusResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:advice:request:v2.0", className = "es.seap.minhap.portafirmas.ws.advice.request.UpdateRequestStatusResponse")
    @RequestWrapper(localName = "updateRequestStatus", targetNamespace = "urn:juntadeandalucia:cice:pfirma:advice:request:v2.0", className = "es.seap.minhap.portafirmas.ws.advice.request.UpdateRequestStatus")
    @WebResult(name = "result", targetNamespace = "")
    @WebMethod    
    public Boolean updateRequestStatus(
    		@WebParam(name = "authentication", targetNamespace = "") Authentication authentication,
    		@WebParam(name = "request", targetNamespace = "") Request request,
    		@WebParam(name = "signature", targetNamespace = "") Signature[] signature)
            throws PfirmaException;


}
