/* Copyright (C) 2012-13 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */

package es.seap.minhap.portafirmas.ws.csvstorage.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2019-01-10T13:35:36.199+01:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0", name = "CSVDocumentWSService")
@XmlSeeAlso({ObjectFactory.class})
public interface CSVDocumentWSService {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "consultarDocumentoResponse", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0", partName = "parameters")
    @WebMethod(action = "urn:consultarDocumento")
    public ConsultarDocumentoResponse consultarDocumento(
        @WebParam(partName = "parameters", name = "consultarDocumento", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
        ConsultarDocumento parameters
    ) throws CSVStorageException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "guardarDocumentoEniResponse", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0", partName = "parameters")
    @WebMethod(action = "urn:guardarDocumentoENI")
    public GuardarDocumentoEniResponse guardarDocumentoENI(
        @WebParam(partName = "parameters", name = "guardarDocumentoENI", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
        GuardarDocumentoENI parameters
    ) throws CSVStorageException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "eliminarDocumentoResponse", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0", partName = "parameters")
    @WebMethod(action = "urn:eliminarDocumento")
    public EliminarDocumentoResponse eliminarDocumento(
        @WebParam(partName = "parameters", name = "eliminarDocumento", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
        EliminarDocumento parameters
    ) throws CSVStorageException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "guardarDocumentoResponse", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0", partName = "parameters")
    @WebMethod(action = "urn:guardarDocumento")
    public GuardarDocumentoResponse guardarDocumento(
        @WebParam(partName = "parameters", name = "guardarDocumento", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
        GuardarDocumento parameters
    ) throws CSVStorageException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "modificarDocumentoEniResponse", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0", partName = "parameters")
    @WebMethod(action = "urn:modificarDocumentoENI")
    public GuardarDocumentoEniResponse modificarDocumentoENI(
        @WebParam(partName = "parameters", name = "modificarDocumentoENI", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
        ModificarDocumentoENI parameters
    ) throws CSVStorageException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "modificarDocumentoResponse", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0", partName = "parameters")
    @WebMethod(action = "urn:modificarDocumento")
    public GuardarDocumentoResponse modificarDocumento(
        @WebParam(partName = "parameters", name = "modificarDocumento", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
        ModificarDocumento parameters
    ) throws CSVStorageException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "otorgarPermisoConsultaResponse", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0", partName = "parameters")
    @WebMethod(action = "urn:otorgarPermisoConsulta")
    public GuardarDocumentoResponse otorgarPermisoConsulta(
        @WebParam(partName = "parameters", name = "otorgarPermisoConsulta", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
        OtorgarPermisoConsulta parameters
    ) throws CSVStorageException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "revocarPermisoConsultaResponse", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0", partName = "parameters")
    @WebMethod(action = "urn:otorgarPermisoConsulta")
    public GuardarDocumentoResponse revocarPermisoConsulta(
        @WebParam(partName = "parameters", name = "revocarPermisoConsulta", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
        RevocarPermisoConsulta parameters
    ) throws CSVStorageException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "consultarPermisosDocumentoResponse", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0", partName = "parameters")
    @WebMethod(action = "urn:consultarPermisosDocumento")
    public ConsultarPermisosDocumentoResponse consultarPermisosDocumento(
        @WebParam(partName = "parameters", name = "consultarPermisosDocumento", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
        ConsultarPermisosDocumento parameters
    ) throws CSVStorageException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "obtenerDocumentoEniResponse", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0", partName = "parameters")
    @WebMethod(action = "urn:obtenerDocumentoENI")
    public ObtenerDocumentoEniResponse obtenerDocumentoENI(
        @WebParam(partName = "parameters", name = "obtenerDocumentoENI", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
        ObtenerDocumentoENI parameters
    ) throws CSVStorageException_Exception;

    @WebResult(name = "documentoTamanioResponse", targetNamespace = "")
    @RequestWrapper(localName = "obtenerTamanioDocumento", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0", className = "es.seap.minhap.portafirmas.ws.csvstorage.client.ObtenerTamanioDocumento")
    @WebMethod(action = "urn:obtenerTamanioDocumento")
    @ResponseWrapper(localName = "obtenerTamanioDocumentoResponse", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0", className = "es.seap.minhap.portafirmas.ws.csvstorage.client.ObtenerTamanioDocumentoResponse")
    public es.seap.minhap.portafirmas.ws.csvstorage.client.TamanioDocumentoResponse obtenerTamanioDocumento(
        @WebParam(name = "obtenerDocumentoRequest", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.csvstorage.client.ObtenerDocumentoRequest obtenerDocumentoRequest
    ) throws CSVStorageException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "obtenerDocumentoResponse", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0", partName = "parameters")
    @WebMethod(action = "urn:obtenerDocumento")
    public ObtenerDocumentoResponse obtenerDocumento(
        @WebParam(partName = "parameters", name = "obtenerDocumento", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
        ObtenerDocumento parameters
    ) throws CSVStorageException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "consultarAplicacionesResponse", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0", partName = "parameters")
    @WebMethod(action = "urn:consultarAplicaciones")
    public ConsultarAplicacionesResponse consultarAplicaciones(
        @WebParam(partName = "parameters", name = "consultarAplicaciones", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
        ConsultarAplicaciones parameters
    ) throws CSVStorageException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "convertirDocumentoEniResponse", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0", partName = "parameters")
    @WebMethod(action = "urn:convertirDocumentoAEni")
    public ConvertirDocumentoEniResponse convertirDocumentoAEni(
        @WebParam(partName = "parameters", name = "convertirDocumentoAEni", targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
        ConvertirDocumentoAEni parameters
    ) throws CSVStorageException_Exception;
}
