
package es.map.directorio.manager.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SC01UN_VolcadoDatosBasicosService", targetNamespace = "http://impl.manager.directorio.map.es", wsdlLocation = "file:/D:/shared/wsdl2java/SC01UN_VolcadoDatosBasicos.wsdl")
public class SC01UNVolcadoDatosBasicosService
    extends Service
{

    private final static URL SC01UNVOLCADODATOSBASICOSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.map.directorio.manager.impl.SC01UNVolcadoDatosBasicosService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.map.directorio.manager.impl.SC01UNVolcadoDatosBasicosService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/shared/wsdl2java/SC01UN_VolcadoDatosBasicos.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/shared/wsdl2java/SC01UN_VolcadoDatosBasicos.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SC01UNVOLCADODATOSBASICOSSERVICE_WSDL_LOCATION = url;
    }

    public SC01UNVolcadoDatosBasicosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SC01UNVolcadoDatosBasicosService() {
        super(SC01UNVOLCADODATOSBASICOSSERVICE_WSDL_LOCATION, new QName("http://impl.manager.directorio.map.es", "SC01UN_VolcadoDatosBasicosService"));
    }

    /**
     * 
     * @return
     *     returns SC01UNVolcadoDatosBasicos
     */
    @WebEndpoint(name = "SC01UN_VolcadoDatosBasicos")
    public SC01UNVolcadoDatosBasicos getSC01UNVolcadoDatosBasicos() {
        return super.getPort(new QName("http://impl.manager.directorio.map.es", "SC01UN_VolcadoDatosBasicos"), SC01UNVolcadoDatosBasicos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SC01UNVolcadoDatosBasicos
     */
    @WebEndpoint(name = "SC01UN_VolcadoDatosBasicos")
    public SC01UNVolcadoDatosBasicos getSC01UNVolcadoDatosBasicos(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.manager.directorio.map.es", "SC01UN_VolcadoDatosBasicos"), SC01UNVolcadoDatosBasicos.class, features);
    }

}
