
package es.map.directorio.manager.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import es.map.directorio.manager.impl.wsexport.ObjectFactory;
import es.map.directorio.manager.impl.wsexport.RespuestaWS;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SC01UN_VolcadoDatosBasicos", targetNamespace = "http://impl.manager.directorio.map.es")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SC01UNVolcadoDatosBasicos {


    /**
     * 
     * @param tipoEntPublica
     * @param tipoUnidadOrg
     * @param comunidadAut
     * @param unidadOrganica
     * @param tipoRelacionUnidad
     * @param estadoUo
     * @param tipoConsulta
     * @param password
     * @param ambito
     * @param formatoFichero
     * @param login
     * @param nivelAdmin
     * @param provinciaCompet
     * @return
     *     returns es.map.directorio.manager.impl.wsexport.RespuestaWS
     */
    @WebMethod
    @WebResult(name = "exportarReturn", partName = "exportarReturn")
    public RespuestaWS exportar(
        @WebParam(name = "login", partName = "login")
        String login,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "formatoFichero", partName = "formatoFichero")
        String formatoFichero,
        @WebParam(name = "tipoConsulta", partName = "tipoConsulta")
        String tipoConsulta,
        @WebParam(name = "estadoUo", partName = "estadoUo")
        String estadoUo,
        @WebParam(name = "nivelAdmin", partName = "nivelAdmin")
        String nivelAdmin,
        @WebParam(name = "ambito", partName = "ambito")
        String ambito,
        @WebParam(name = "comunidadAut", partName = "comunidadAut")
        String comunidadAut,
        @WebParam(name = "provinciaCompet", partName = "provinciaCompet")
        String provinciaCompet,
        @WebParam(name = "tipoUnidadOrg", partName = "tipoUnidadOrg")
        String tipoUnidadOrg,
        @WebParam(name = "tipoEntPublica", partName = "tipoEntPublica")
        String tipoEntPublica,
        @WebParam(name = "unidadOrganica", partName = "unidadOrganica")
        String unidadOrganica,
        @WebParam(name = "tipoRelacionUnidad", partName = "tipoRelacionUnidad")
        String tipoRelacionUnidad);

}
