//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.18 at 02:19:57 PM CET 
//


package es.dipucr.jaxb.juntaconsultiva.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}departamento"/>
 *       &lt;/sequence>
 *       &lt;attribute name="codEnteContratante" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="nombreEnteContratante" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "departamento"
})
@XmlRootElement(name = "enteContratante")
public class EnteContratante {

    @XmlElement(required = true)
    protected Departamento departamento;
    @XmlAttribute(name = "codEnteContratante", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String codEnteContratante;
    @XmlAttribute(name = "nombreEnteContratante", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String nombreEnteContratante;

    /**
     * Gets the value of the departamento property.
     * 
     * @return
     *     possible object is
     *     {@link Departamento }
     *     
     */
    public Departamento getDepartamento() {
        return departamento;
    }

    /**
     * Sets the value of the departamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Departamento }
     *     
     */
    public void setDepartamento(Departamento value) {
        this.departamento = value;
    }

    /**
     * Gets the value of the codEnteContratante property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodEnteContratante() {
        return codEnteContratante;
    }

    /**
     * Sets the value of the codEnteContratante property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodEnteContratante(String value) {
        this.codEnteContratante = value;
    }

    /**
     * Gets the value of the nombreEnteContratante property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreEnteContratante() {
        return nombreEnteContratante;
    }

    /**
     * Sets the value of the nombreEnteContratante property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreEnteContratante(String value) {
        this.nombreEnteContratante = value;
    }

}
