cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionAdministracionWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skin/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinDefecto/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_001/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_002/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_003/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_004/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_005/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_007/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_008/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_009/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_010/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_013/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_026/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_030/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_037/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_040/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_044/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_047/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_057/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_060/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_061/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/WEB-INF/classes/SIGEM_AutenticacionWeb/skinEntidad_062/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_ConsultaRegistroTelematicoBackOfficeWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_ConsultaRegistroTelematicoBackOfficeWeb/WEB-INF/classes/SIGEM_ConsultaRegistroTelematicoBackOfficeWeb/skin/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_CatalogoTramitesWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AdministracionUsuariosWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skin/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinDefecto/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_001/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_002/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_003/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_004/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_005/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_007/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_008/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_009/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_010/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_013/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_026/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_030/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_037/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_040/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_044/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_047/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_057/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_060/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_061/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_061/Ayto_Logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/WEB-INF/classes/SIGEM_AutenticacionBackOfficeWeb/skinEntidad_062/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_CatalogoProcedimientosWeb/ispac/skin1/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_CatalogoProcedimientosWeb/WEB-INF/classes/SIGEM_CatalogoProcedimientosWeb/skinDefecto/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_CatalogoProcedimientosWeb/WEB-INF/classes/SIGEM_CatalogoProcedimientosWeb/skinEntidad_000/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_EstructuraWeb/include/images/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroPresencialAdminWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_PublicadorWeb/ispac/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_PublicadorWeb/WEB-INF/classes/SIGEM_PublicadorWeb/skinDefecto/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_PublicadorWeb/WEB-INF/classes/SIGEM_PublicadorWeb/skinEntidad_000/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroPresencialWeb/help/10/graficos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroPresencialWeb/help/3/graficos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroPresencialWeb/help/45/graficos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroPresencialWeb/help/7/graficos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroPresencialWeb/images/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroPresencialWeb/WEB-INF/classes/SIGEM_RegistroPresencialWeb/skinDefecto/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroPresencialWeb/WEB-INF/classes/SIGEM_RegistroPresencialWeb/skinEntidad_000/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_SchedulerWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_PublicadorWS/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_CertificacionWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_CertificacionWeb/WEB-INF/classes/SIGEM_CertificacionWeb/skin/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_TramitacionWeb/ispac/skin1/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_TramitacionWeb/WEB-INF/classes/SIGEM_TramitacionWeb/skinDefecto/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_TramitacionWeb/WEB-INF/classes/SIGEM_TramitacionWeb/skinEntidad_000/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_TramitacionWS/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_ConsultaRegistroTelematicoWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_ConsultaRegistroTelematicoWeb/WEB-INF/classes/SIGEM_ConsultaRegistroTelematicoWeb/skin/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_ConsultaWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_ConsultaWeb/WEB-INF/classes/SIGEM_ConsultaWeb/skin/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_GestionCSVWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_GestionCSVWeb/WEB-INF/classes/SIGEM_GestionCSVWeb/skin/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_GestionCSVWeb/WEB-INF/classes/SIGEM_GestionCSVWeb/skinDefecto/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_GestionCSVWeb/WEB-INF/classes/SIGEM_GestionCSVWeb/skinEntidad_000/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/tramites/000/BOP_1/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/tramites/000/BOP_1_BDNS/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/tramites/000/DPCR_RH_CERT/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/tramites/000/DPCR_SRS/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/WEB-INF/classes/SIGEM_RegistroTelematicoWeb/skin/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/WEB-INF/classes/SIGEM_RegistroTelematicoWeb/skinDefecto/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/WEB-INF/classes/SIGEM_RegistroTelematicoWeb/skinEntidad_000/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_AdministracionWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_BuscadorDocsWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_BuscadorDocsWeb/WEB-INF/classes/SIGEM_BuscadorDocsWeb/skinDefecto/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_BuscadorDocsWeb/WEB-INF/classes/SIGEM_BuscadorDocsWeb/skinEntidad_000/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_ConsultaExpedienteBackOfficeWeb/img/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/SIGEM_ConsultaExpedienteBackOfficeWeb/WEB-INF/classes/SIGEM_ConsultaExpedienteBackOfficeWeb/skin/logos/logo.gif
cp $HOME/logos/logo_pruebas.gif $HOME/tomcat7/webapps/portal/img/logo.gif