
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_AutenticacionWeb/img/Minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_ConsultaRegistroTelematicoBackOfficeWeb/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_CatalogoTramitesWeb/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_AdministracionUsuariosWeb/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_AutenticacionBackOfficeWeb/img/Minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_EstructuraWeb/include/images/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_RegistroPresencialAdminWeb/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_PublicadorWeb/ispac/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_RegistroPresencialWeb/images/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_SchedulerWeb/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_CertificacionWeb/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_TramitacionWeb/ispac/skin1/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_TramitacionWS/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_ConsultaRegistroTelematicoWeb/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_ConsultaWeb/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_GestionCSVWeb/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_RegistroTelematicoWeb/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_AdministracionWeb/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_BuscadorDocsWeb/img/minetur.jpg
cp $HOME/logos/logos_originales/Minetur.jpg $HOME/tomcat7/webapps/SIGEM_ConsultaExpedienteBackOfficeWeb/img/minetur.jpg