/* Copyright (C) 2012-13 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */

package es.seap.minhap.portafirmas.ws.afirma5.dssafirmaverify.client.oasis.names.tc.dss._1_0.core.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.0
 * Thu Jul 12 08:48:05 CEST 2012
 * Generated source version: 2.3.0
 * 
 */
 
@WebService(targetNamespace = "urn:oasis:names:tc:dss:1.0:core:schema", name = "DSSSignature")
@XmlSeeAlso({ObjectFactory.class, 
	es.seap.minhap.portafirmas.ws.afirma5.dssafirmaverify.client.oasis.names.tc.dss._1_0.profiles.verificationreport.schema.ObjectFactory.class, 
	es.seap.minhap.portafirmas.ws.afirma5.dssafirmaverify.client.afirma.dss._1_0.profile.xss.schema.ObjectFactory.class, 
	es.seap.minhap.portafirmas.ws.afirma5.dssafirmaverify.client.org.etsi.uri._01903.v1_3.ObjectFactory.class, 
	es.seap.minhap.portafirmas.ws.afirma5.dssafirmaverify.client.org.etsi.uri._02231.v2.ObjectFactory.class, 
	es.seap.minhap.portafirmas.ws.afirma5.dssafirmaverify.client.org.w3._2000._09.xmldsig.ObjectFactory.class, 
	es.seap.minhap.portafirmas.ws.afirma5.dssafirmaverify.client.oasis.names.tc.saml._1_0.assertion.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DSSSignature {

    @WebResult(name = "verifyReturn", targetNamespace = "urn:oasis:names:tc:dss:1.0:core:schema", partName = "verifyReturn")
    @WebMethod
    public java.lang.String verify(
        @WebParam(partName = "dssXML", name = "dssXML")
        java.lang.String dssXML
    );
}
