
package es.msssi.sgm.registropresencial.connector.antivirus.beans;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AntivirusServices", targetNamespace = "http://msps/antivirus/ws", wsdlLocation = "AntivirusImpl.xml")
public class AntivirusServices
    extends Service
{

    private final static URL ANTIVIRUSSERVICES_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.msssi.sgm.registropresencial.connector.antivirus.beans.AntivirusServices.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.msssi.sgm.registropresencial.connector.antivirus.beans.AntivirusServices.class.getResource(".");
            url = new URL(baseUrl, "AntivirusImpl.xml");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'AntivirusImpl.xml', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ANTIVIRUSSERVICES_WSDL_LOCATION = url;
    }

    public AntivirusServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AntivirusServices() {
        super(ANTIVIRUSSERVICES_WSDL_LOCATION, new QName("http://msps/antivirus/ws", "AntivirusServices"));
    }

    /**
     * 
     * @return
     *     returns AntivirusPortType
     */
    @WebEndpoint(name = "AntivirusPortTypeSoapPort")
    public AntivirusPortType getAntivirusPortTypeSoapPort() {
        return super.getPort(new QName("http://msps/antivirus/ws", "AntivirusPortTypeSoapPort"), AntivirusPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AntivirusPortType
     */
    @WebEndpoint(name = "AntivirusPortTypeSoapPort")
    public AntivirusPortType getAntivirusPortTypeSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://msps/antivirus/ws", "AntivirusPortTypeSoapPort"), AntivirusPortType.class, features);
    }

}
