/* Copyright (C) 2012-13 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */

package juntadeandalucia.cice.pfirma.advice.v2_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.0
 * Wed Dec 21 16:04:45 CET 2011
 * Generated source version: 2.3.0
 * 
 */
 
@WebService(targetNamespace = "urn:juntadeandalucia:cice:pfirma:advice:v2.0", name = "AdviceService")
@XmlSeeAlso({juntadeandalucia.cice.pfirma.type.v2.ObjectFactory.class, juntadeandalucia.cice.pfirma.advice.request.v2.ObjectFactory.class})
public interface AdviceService {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateRequestStatus", targetNamespace = "urn:juntadeandalucia:cice:pfirma:advice:request:v2.0", className = "juntadeandalucia.cice.pfirma.advice.request.v2.UpdateRequestStatus")
    @WebMethod
    @ResponseWrapper(localName = "updateRequestStatusResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:advice:request:v2.0", className = "juntadeandalucia.cice.pfirma.advice.request.v2.UpdateRequestStatusResponse")
    public java.lang.Boolean updateRequestStatus(
        @WebParam(name = "authentication", targetNamespace = "")
        juntadeandalucia.cice.pfirma.type.v2.Authentication authentication,
        @WebParam(name = "request", targetNamespace = "")
        juntadeandalucia.cice.pfirma.type.v2.Request request,
        @WebParam(name = "signature", targetNamespace = "")
        java.util.List<juntadeandalucia.cice.pfirma.type.v2.Signature> signature
    ) throws PfirmaException;
}
