/* Copyright (C) 2012-13 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */


/*
 * 
 */

package juntadeandalucia.cice.pfirma.advice.v2_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.0
 * Wed Dec 21 16:04:45 CET 2011
 * Generated source version: 2.3.0
 * 
 */


@WebServiceClient(name = "AdviceService", 
                  wsdlLocation = "file:AdviceService.wsdl",
                  targetNamespace = "urn:juntadeandalucia:cice:pfirma:advice:v2.0") 
public class AdviceService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("urn:juntadeandalucia:cice:pfirma:advice:v2.0", "AdviceService");
    public final static QName AdviceServicePort = new QName("urn:juntadeandalucia:cice:pfirma:advice:v2.0", "AdviceServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:AdviceService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:AdviceService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AdviceService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdviceService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdviceService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
//    public AdviceService_Service(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }
//    public AdviceService_Service(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }
//
//    public AdviceService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     * 
     * @return
     *     returns AdviceService
     */
    @WebEndpoint(name = "AdviceServicePort")
    public AdviceService getAdviceServicePort() {
        return super.getPort(AdviceServicePort, AdviceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdviceService
     */
    @WebEndpoint(name = "AdviceServicePort")
    public AdviceService getAdviceServicePort(WebServiceFeature... features) {
        return super.getPort(AdviceServicePort, AdviceService.class, features);
    }

}
