/* Copyright (C) 2012-13 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */


package es.gob.aapp.csvbroker.webservices.querydocument.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.springframework.stereotype.Service;

import es.gob.aapp.csvbroker.webservices.querydocument.model.v1.CSVQueryDocumentRequest;
import es.gob.aapp.csvbroker.webservices.querydocument.model.v1.CSVQueryDocumentResponse;
import es.gob.aapp.csvbroker.webservices.querydocument.model.v1.WSCredential;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */

@WebService(name = "CSVQueryDocumentService", targetNamespace = "urn:es:gob:aapp:csvbroker:webservices:querydocument:v1.0")
@XmlSeeAlso({
    es.gob.aapp.csvbroker.webservices.querydocument.model.v1.ObjectFactory.class,
    es.gob.aapp.csvbroker.webservices.querydocument.v1.ObjectFactory.class
})
public interface CSVQueryDocumentService {


    /**
     * 
     * @param queryDocumentRequest
     * @param credential
     * @return
     *     returns es.gob.aapp.csvbroker.webservices.querydocument.model.v1.CSVQueryDocumentResponse
     * @throws CSVQueryDocumentException
     */
    @WebMethod
    @WebResult(name = "CSVQueryDocumentResponse", targetNamespace = "urn:es:gob:aapp:csvbroker:webservices:querydocument:model:v1.0")
    @RequestWrapper(localName = "csvQueryDocument", targetNamespace = "urn:es:gob:aapp:csvbroker:webservices:querydocument:v1.0", className = "es.gob.aapp.csvbroker.webservices.querydocument.v1.CsvQueryDocument")
    @ResponseWrapper(localName = "csvQueryDocumentResponse", targetNamespace = "urn:es:gob:aapp:csvbroker:webservices:querydocument:v1.0", className = "es.gob.aapp.csvbroker.webservices.querydocument.v1.CsvQueryDocumentResponse")
    public CSVQueryDocumentResponse csvQueryDocument(
        @WebParam(name = "credential", targetNamespace = "")
        WSCredential credential,
        @WebParam(name = "queryDocumentRequest", targetNamespace = "")
        CSVQueryDocumentRequest queryDocumentRequest)
        throws CSVQueryDocumentException
    ;

}
