//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.eu.stork.names.tc.stork._1_0.assertion;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for canonicalAddressType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="canonicalAddressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="countryCodeAddress" type="{urn:eu:stork:names:tc:STORK:1.0:assertion}CountryCodeType"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="municipalityCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="town" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="postalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="streetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="streetNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="apartmentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "canonicalAddressType", propOrder = {
    "countryCodeAddress",
    "state",
    "municipalityCode",
    "town",
    "postalCode",
    "streetName",
    "streetNumber",
    "apartmentNumber"
})
public class CanonicalAddressType {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String countryCodeAddress;
    protected String state;
    protected String municipalityCode;
    @XmlElement(required = true)
    protected String town;
    @XmlElement(required = true)
    protected String postalCode;
    @XmlElement(required = true)
    protected String streetName;
    protected String streetNumber;
    protected String apartmentNumber;

    /**
     * Gets the value of the countryCodeAddress property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCountryCodeAddress() {
        return countryCodeAddress;
    }

    /**
     * Sets the value of the countryCodeAddress property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCountryCodeAddress(String value) {
        this.countryCodeAddress = value;
    }

    /**
     * Gets the value of the state property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the municipalityCode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMunicipalityCode() {
        return municipalityCode;
    }

    /**
     * Sets the value of the municipalityCode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMunicipalityCode(String value) {
        this.municipalityCode = value;
    }

    /**
     * Gets the value of the town property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTown() {
        return town;
    }

    /**
     * Sets the value of the town property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTown(String value) {
        this.town = value;
    }

    /**
     * Gets the value of the postalCode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the streetName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * Sets the value of the streetName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setStreetName(String value) {
        this.streetName = value;
    }

    /**
     * Gets the value of the streetNumber property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getStreetNumber() {
        return streetNumber;
    }

    /**
     * Sets the value of the streetNumber property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setStreetNumber(String value) {
        this.streetNumber = value;
    }

    /**
     * Gets the value of the apartmentNumber property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getApartmentNumber() {
        return apartmentNumber;
    }

    /**
     * Sets the value of the apartmentNumber property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setApartmentNumber(String value) {
        this.apartmentNumber = value;
    }

}
