//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.eu.stork.names.tc.stork._1_0.assertion;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for isAcademicStaffType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="isAcademicStaffType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nameOfInstitution" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="occupation" type="{urn:eu:stork:names:tc:STORK:1.0:assertion}occupationType"/>
 *         &lt;element name="knowledgeArea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AQAA" type="{urn:eu:stork:names:tc:STORK:1.0:assertion}QualityAuthenticationAssuranceLevelType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "isAcademicStaffType", propOrder = {
    "nameOfInstitution",
    "occupation",
    "knowledgeArea",
    "aqaa"
})
public class IsAcademicStaffType {

    @XmlElement(required = true)
    protected String nameOfInstitution;
    @XmlElement(required = true)
    protected String occupation;
    protected String knowledgeArea;
    @XmlElement(name = "AQAA")
    protected int aqaa;

    /**
     * Gets the value of the nameOfInstitution property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNameOfInstitution() {
        return nameOfInstitution;
    }

    /**
     * Sets the value of the nameOfInstitution property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNameOfInstitution(String value) {
        this.nameOfInstitution = value;
    }

    /**
     * Gets the value of the occupation property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * Sets the value of the occupation property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setOccupation(String value) {
        this.occupation = value;
    }

    /**
     * Gets the value of the knowledgeArea property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getKnowledgeArea() {
        return knowledgeArea;
    }

    /**
     * Sets the value of the knowledgeArea property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setKnowledgeArea(String value) {
        this.knowledgeArea = value;
    }

    /**
     * Gets the value of the aqaa property.
     *
     */
    public int getAQAA() {
        return aqaa;
    }

    /**
     * Sets the value of the aqaa property.
     *
     */
    public void setAQAA(int value) {
        this.aqaa = value;
    }

}
