/*
* Copyright 2016 Ministerio de Sanidad, Servicios Sociales e Igualdad 
* Licencia con arreglo a la EUPL, Versión 1.1 o –en cuanto sean aprobadas por laComisión Europea– versiones posteriores de la EUPL (la «Licencia»); 
* Solo podrá usarse esta obra si se respeta la Licencia. 
* Puede obtenerse una copia de la Licencia en: 
* http://joinup.ec.europa.eu/software/page/eupl/licence-eupl 
* Salvo cuando lo exija la legislación aplicable o se acuerde por escrito, el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL», SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas. 
* Véase la Licencia en el idioma concreto que rige los permisos y limitaciones que establece la Licencia. 
*/

package es.msssi.dir3.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "ConsultServiceService", targetNamespace = "http://ws.dir3.msssi.es/",
    wsdlLocation = "http://127.0.0.1:7001/dir3WS/consultService?wsdl")
public class ConsultServiceService extends Service {

    private final static URL CONSULTSERVICESERVICE_WSDL_LOCATION;
    private final static Logger LOG = Logger
	.getLogger(es.msssi.dir3.ws.ConsultServiceService.class.getName());

    static {
	URL url = null;
	try {
	    URL baseUrl;
	    baseUrl = es.msssi.dir3.ws.ConsultServiceService.class.getResource(".");
	    url = new URL(
		baseUrl, "http://127.0.0.1:7001/dir3WS/consultService?wsdl");
	}
	catch (MalformedURLException e) {
	    LOG
		.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:7001/dir3WS/consultService?wsdl', retrying as a local file");
	    LOG.warning(e.getMessage());
	}
	CONSULTSERVICESERVICE_WSDL_LOCATION = url;
    }

    public ConsultServiceService(URL wsdlLocation, QName serviceName) {
	super(wsdlLocation, serviceName);
    }

    public ConsultServiceService() {
	super(CONSULTSERVICESERVICE_WSDL_LOCATION, new QName(
	    "http://ws.dir3.msssi.es/", "ConsultServiceService"));
    }

    /**
     * 
     * @return returns ConsultService
     */
    @WebEndpoint(name = "ConsultServicePort")
    public ConsultService getConsultServicePort() {
	return super.getPort(
	    new QName(
		"http://ws.dir3.msssi.es/", "ConsultServicePort"), ConsultService.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns ConsultService
     */
    @WebEndpoint(name = "ConsultServicePort")
    public ConsultService getConsultServicePort(
	WebServiceFeature... features) {
	return super.getPort(
	    new QName(
		"http://ws.dir3.msssi.es/", "ConsultServicePort"), ConsultService.class, features);
    }

}
