/*
* Copyright 2016 Ministerio de Sanidad, Servicios Sociales e Igualdad 
* Licencia con arreglo a la EUPL, Versión 1.1 o –en cuanto sean aprobadas por laComisión Europea– versiones posteriores de la EUPL (la «Licencia»); 
* Solo podrá usarse esta obra si se respeta la Licencia. 
* Puede obtenerse una copia de la Licencia en: 
* http://joinup.ec.europa.eu/software/page/eupl/licence-eupl 
* Salvo cuando lo exija la legislación aplicable o se acuerde por escrito, el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL», SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas. 
* Véase la Licencia en el idioma concreto que rige los permisos y limitaciones que establece la Licencia. 
*/

package es.msssi.dir3.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import consultservice.ws.dir3.msssi.es.consultbasicdataofresponse.ConsultBasicDataOFResponse;
import consultservice.ws.dir3.msssi.es.consultbasicdatauoresponse.ConsultBasicDataUOResponse;
import consultservice.ws.dir3.msssi.es.consultofrequest.ConsultOFRequest;
import consultservice.ws.dir3.msssi.es.consultofresponse.ConsultOFResponse;
import consultservice.ws.dir3.msssi.es.consultuorequest.ConsultUORequest;
import consultservice.ws.dir3.msssi.es.consultuoresponse.ConsultUOResponse;
import consultservice.ws.dir3.msssi.es.countofrequest.CountOFRequest;
import consultservice.ws.dir3.msssi.es.countresponse.CountResponse;
import consultservice.ws.dir3.msssi.es.countuorequest.CountUORequest;
import consultservice.ws.dir3.msssi.es.getofrequest.GetOFRequest;
import consultservice.ws.dir3.msssi.es.getofresponse.GetOFResponse;
import consultservice.ws.dir3.msssi.es.getuorequest.GetUORequest;
import consultservice.ws.dir3.msssi.es.getuoresponse.GetUOResponse;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebService(name = "ConsultService", targetNamespace = "http://ws.dir3.msssi.es/")
@XmlSeeAlso({ consultservice.ws.dir3.msssi.es.countresponse.ObjectFactory.class,
    consultservice.ws.dir3.msssi.es.getuorequest.ObjectFactory.class,
    consultservice.ws.dir3.msssi.es.consultbasicdatauoresponse.ObjectFactory.class,
    consultservice.ws.dir3.msssi.es.consultuorequest.ObjectFactory.class,
    consultservice.ws.dir3.msssi.es.getofrequest.ObjectFactory.class,
    consultservice.ws.dir3.msssi.es.consultofresponse.ObjectFactory.class,
    consultservice.ws.dir3.msssi.es.getofresponse.ObjectFactory.class,
    consultservice.ws.dir3.msssi.es.consultuoresponse.ObjectFactory.class,
    consultservice.ws.dir3.msssi.es.getuoresponse.ObjectFactory.class,
    consultservice.ws.dir3.msssi.es.countofrequest.ObjectFactory.class,
    es.msssi.dir3.ws.ObjectFactory.class,
    consultservice.ws.dir3.msssi.es.countuorequest.ObjectFactory.class,
    consultservice.ws.dir3.msssi.es.consultbasicdataofresponse.ObjectFactory.class,
    consultservice.ws.dir3.msssi.es.consultofrequest.ObjectFactory.class })
public interface ConsultService {

    /**
     * 
     * @param request
     * @return returns
     *         consultservice.ws.dir3.msssi.es.getuoresponse.GetUOResponse
     * @throws Dir3WSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUnit", targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.GetUnit")
    @ResponseWrapper(localName = "getUnitResponse", targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.GetUnitResponse")
    public GetUOResponse getUnit(
	@WebParam(name = "request", targetNamespace = "") GetUORequest request)
	throws Dir3WSException_Exception;

    /**
     * 
     * @param request
     * @return returns
     *         consultservice.ws.dir3.msssi.es.countresponse.CountResponse
     * @throws Dir3WSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countOffices", targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.CountOffices")
    @ResponseWrapper(localName = "countOfficesResponse",
	targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.CountOfficesResponse")
    public CountResponse countOffices(
	@WebParam(name = "request", targetNamespace = "") CountOFRequest request)
	throws Dir3WSException_Exception;

    /**
     * 
     * @param request
     * @return returns
     *         consultservice.ws.dir3.msssi.es.consultofresponse.ConsultOFResponse
     * @throws Dir3WSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findOffices", targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.FindOffices")
    @ResponseWrapper(localName = "findOfficesResponse",
	targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.FindOfficesResponse")
    public ConsultOFResponse findOffices(
	@WebParam(name = "request", targetNamespace = "") ConsultOFRequest request)
	throws Dir3WSException_Exception;

    /**
     * 
     * @param request
     * @return returns
     *         consultservice.ws.dir3.msssi.es.getofresponse.GetOFResponse
     * @throws Dir3WSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOffice", targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.GetOffice")
    @ResponseWrapper(localName = "getOfficeResponse", targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.GetOfficeResponse")
    public GetOFResponse getOffice(
	@WebParam(name = "request", targetNamespace = "") GetOFRequest request)
	throws Dir3WSException_Exception;

    /**
     * 
     * @param request
     * @return returns
     *         consultservice.ws.dir3.msssi.es.countresponse.CountResponse
     * @throws Dir3WSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countUnits", targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.CountUnits")
    @ResponseWrapper(localName = "countUnitsResponse",
	targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.CountUnitsResponse")
    public CountResponse countUnits(
	@WebParam(name = "request", targetNamespace = "") CountUORequest request)
	throws Dir3WSException_Exception;

    /**
     * 
     * @param request
     * @return returns
     *         consultservice.ws.dir3.msssi.es.consultuoresponse.ConsultUOResponse
     * @throws Dir3WSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUnits", targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.FindUnits")
    @ResponseWrapper(localName = "findUnitsResponse", targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.FindUnitsResponse")
    public ConsultUOResponse findUnits(
	@WebParam(name = "request", targetNamespace = "") ConsultUORequest request)
	throws Dir3WSException_Exception;

    /**
     * 
     * @param request
     * @return returns
     *         consultservice.ws.dir3.msssi.es.consultbasicdataofresponse
     *         .ConsultBasicDataOFResponse
     * @throws Dir3WSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findBasicDataOffices",
	targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.FindBasicDataOffices")
    @ResponseWrapper(localName = "findBasicDataOfficesResponse",
	targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.FindBasicDataOfficesResponse")
    public ConsultBasicDataOFResponse findBasicDataOffices(
	@WebParam(name = "request", targetNamespace = "") ConsultOFRequest request)
	throws Dir3WSException_Exception;

    /**
     * 
     * @param request
     * @return returns
     *         consultservice.ws.dir3.msssi.es.consultbasicdatauoresponse
     *         .ConsultBasicDataUOResponse
     * @throws Dir3WSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findBasicDataUnits", targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.FindBasicDataUnits")
    @ResponseWrapper(localName = "findBasicDataUnitsResponse",
	targetNamespace = "http://ws.dir3.msssi.es/",
	className = "es.msssi.dir3.ws.FindBasicDataUnitsResponse")
    public ConsultBasicDataUOResponse findBasicDataUnits(
	@WebParam(name = "request", targetNamespace = "") ConsultUORequest request)
	throws Dir3WSException_Exception;

}
