/*
* Copyright 2016 Ministerio de Sanidad, Servicios Sociales e Igualdad 
* Licencia con arreglo a la EUPL, Versión 1.1 o –en cuanto sean aprobadas por laComisión Europea– versiones posteriores de la EUPL (la «Licencia»); 
* Solo podrá usarse esta obra si se respeta la Licencia. 
* Puede obtenerse una copia de la Licencia en: 
* http://joinup.ec.europa.eu/software/page/eupl/licence-eupl 
* Salvo cuando lo exija la legislación aplicable o se acuerde por escrito, el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL», SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas. 
* Véase la Licencia en el idioma concreto que rige los permisos y limitaciones que establece la Licencia. 
*/

package es.map.directorio.manager.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "SD01UN_DescargaUnidadesService", targetNamespace = "http://impl.manager.directorio.map.es", wsdlLocation = "http://dir3ws.redsara.es/directorio/services/SD01UN_DescargaUnidades?wsdl")
public class SD01UNDescargaUnidadesService extends Service {

    private final static URL SD01UNDESCARGAUNIDADESSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.map.directorio.manager.impl.SD01UNDescargaUnidadesService.class.getName());

    static {
    	URL url = null;
    	try {
    		URL baseUrl;
    		baseUrl = es.map.directorio.manager.impl.SD01UNDescargaUnidadesService.class.getResource(".");
    		url = new URL( baseUrl,		    "http://dir3ws.redsara.es/directorio/services/SD01UN_DescargaUnidades?wsdl");
    	} catch (MalformedURLException e) {
    		logger .warning("Failed to create URL for the wsdl Location: 'http://dir3ws.redsara.es/directorio/services/SD01UN_DescargaUnidades?wsdl', retrying as a local file");
    		logger.warning(e.getMessage());
    	}
    	SD01UNDESCARGAUNIDADESSERVICE_WSDL_LOCATION = url;
    }

    public SD01UNDescargaUnidadesService(URL wsdlLocation, QName serviceName) {
    	super(wsdlLocation, serviceName);
    }

    public SD01UNDescargaUnidadesService() {
    	super(SD01UNDESCARGAUNIDADESSERVICE_WSDL_LOCATION, new QName(
	    "http://impl.manager.directorio.map.es", "SD01UN_DescargaUnidadesService"));
    }

    /**
     * 
     * @return returns SD01UNDescargaUnidades
     */
    @WebEndpoint(name = "SD01UN_DescargaUnidades")
    public SD01UNDescargaUnidades getSD01UNDescargaUnidades() {
    	return super.getPort(new QName( "http://impl.manager.directorio.map.es", "SD01UN_DescargaUnidades"), SD01UNDescargaUnidades.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns SD01UNDescargaUnidades
     */
    @WebEndpoint(name = "SD01UN_DescargaUnidades")
    public SD01UNDescargaUnidades getSD01UNDescargaUnidades( WebServiceFeature... features) {
    	return super.getPort( new QName( "http://impl.manager.directorio.map.es", "SD01UN_DescargaUnidades"), SD01UNDescargaUnidades.class, features);
    }

}
