package es.dipucr.tablonEdictalUnico.quartz.bean;

// Generated 26-may-2015 10:44:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TablonEdictalBoeDatos generated by hbm2java
 */
public class TablonEdictalBoeDatos implements java.io.Serializable {

	private int id;
	private String numexp;
	private String emailIncidencias;
	private String formaPublicacion;
	private String datospersonales;
	private String tipoanuncio;
	private String lgt;
	private String procedimiento;
	private String lugar;
	private String cargonombre;
	private Date fechapublicacion;
	private Date fechafirma;
	private String identificadorboe;
	private String identificadoranuncioboe;
	private String traidoanuncioteu;
	private int id_proc;
	private String uid_destinatario;

	public TablonEdictalBoeDatos() {
	}

	public TablonEdictalBoeDatos(int id, String numexp) {
		this.id = id;
		this.numexp = numexp;
	}

	public TablonEdictalBoeDatos(int id, String numexp,
			String emailIncidencias, String formaPublicacion,
			String datospersonales, String tipoanuncio, String lgt,
			String procedimiento, String lugar, String cargonombre,
			Date fechapublicacion, Date fechafirma, String identificadorboe,
			String identificadoranuncioboe, String traidoanuncioteu) {
		this.id = id;
		this.numexp = numexp;
		this.emailIncidencias = emailIncidencias;
		this.formaPublicacion = formaPublicacion;
		this.datospersonales = datospersonales;
		this.tipoanuncio = tipoanuncio;
		this.lgt = lgt;
		this.procedimiento = procedimiento;
		this.lugar = lugar;
		this.cargonombre = cargonombre;
		this.fechapublicacion = fechapublicacion;
		this.fechafirma = fechafirma;
		this.identificadorboe = identificadorboe;
		this.identificadoranuncioboe = identificadoranuncioboe;
		this.traidoanuncioteu = traidoanuncioteu;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNumexp() {
		return this.numexp;
	}

	public void setNumexp(String numexp) {
		this.numexp = numexp;
	}

	public String getEmailIncidencias() {
		return this.emailIncidencias;
	}

	public void setEmailIncidencias(String emailIncidencias) {
		this.emailIncidencias = emailIncidencias;
	}

	public String getFormaPublicacion() {
		return this.formaPublicacion;
	}

	public void setFormaPublicacion(String formaPublicacion) {
		this.formaPublicacion = formaPublicacion;
	}

	public String getDatospersonales() {
		return this.datospersonales;
	}

	public void setDatospersonales(String datospersonales) {
		this.datospersonales = datospersonales;
	}

	public String getTipoanuncio() {
		return this.tipoanuncio;
	}

	public void setTipoanuncio(String tipoanuncio) {
		this.tipoanuncio = tipoanuncio;
	}

	public String getLgt() {
		return this.lgt;
	}

	public void setLgt(String lgt) {
		this.lgt = lgt;
	}

	public String getProcedimiento() {
		return this.procedimiento;
	}

	public void setProcedimiento(String procedimiento) {
		this.procedimiento = procedimiento;
	}

	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	public String getCargonombre() {
		return this.cargonombre;
	}

	public void setCargonombre(String cargonombre) {
		this.cargonombre = cargonombre;
	}

	public Date getFechapublicacion() {
		return this.fechapublicacion;
	}

	public void setFechapublicacion(Date fechapublicacion) {
		this.fechapublicacion = fechapublicacion;
	}

	public Date getFechafirma() {
		return this.fechafirma;
	}

	public void setFechafirma(Date fechafirma) {
		this.fechafirma = fechafirma;
	}

	public String getIdentificadorboe() {
		return this.identificadorboe;
	}

	public void setIdentificadorboe(String identificadorboe) {
		this.identificadorboe = identificadorboe;
	}

	public String getIdentificadoranuncioboe() {
		return this.identificadoranuncioboe;
	}

	public void setIdentificadoranuncioboe(String identificadoranuncioboe) {
		this.identificadoranuncioboe = identificadoranuncioboe;
	}

	public String getTraidoanuncioteu() {
		return this.traidoanuncioteu;
	}

	public void setTraidoanuncioteu(String traidoanuncioteu) {
		this.traidoanuncioteu = traidoanuncioteu;
	}

	public int getId_proc() {
		return id_proc;
	}

	public void setId_proc(int id_proc) {
		this.id_proc = id_proc;
	}

	public String getUid_destinatario() {
		return uid_destinatario;
	}

	public void setUid_destinatario(String uid_destinatario) {
		this.uid_destinatario = uid_destinatario;
	}

}
