/* Copyright (C) 2012-13 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */

package es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2018-10-18T14:28:04.827+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", name = "GInsideUserTokenWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface GInsideUserTokenWebService {

    @WebResult(name = "expediente", targetNamespace = "")
    @RequestWrapper(localName = "convertirExpedienteAEniAutocontenido", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ConvertirExpedienteAEniAutocontenido")
    @WebMethod(action = "urn:convertirExpedienteAEniAutocontenido")
    @ResponseWrapper(localName = "convertirExpedienteAEniAutocontenidoResponse", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ConvertirExpedienteAEniAutocontenidoResponse")
    public es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ExpedienteEniFileInside convertirExpedienteAEniAutocontenido(
        @WebParam(name = "expediente", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoExpedienteConversionInsideWS expediente,
        @WebParam(name = "contenidoFirma", targetNamespace = "")
        java.lang.String contenidoFirma
    ) throws InsideWSException;

    @WebResult(name = "expediente", targetNamespace = "")
    @RequestWrapper(localName = "convertirExpedienteAEniConMAdicionalesAutocontenido", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ConvertirExpedienteAEniConMAdicionalesAutocontenido")
    @WebMethod(action = "urn:convertirExpedienteAEniConMAdicionalesAutocontenido")
    @ResponseWrapper(localName = "convertirExpedienteAEniConMAdicionalesAutocontenidoResponse", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ConvertirExpedienteAEniConMAdicionalesAutocontenidoResponse")
    public es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ExpedienteEniFileInsideConMAdicionales convertirExpedienteAEniConMAdicionalesAutocontenido(
        @WebParam(name = "expediente", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoExpedienteConversionInsideWS expediente,
        @WebParam(name = "metadatosAdicionales", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoMetadatosAdicionales metadatosAdicionales,
        @WebParam(name = "contenidoFirma", targetNamespace = "")
        java.lang.String contenidoFirma
    ) throws InsideWSException;

    @WebResult(name = "resultadoVisualizacion", targetNamespace = "")
    @RequestWrapper(localName = "visualizarDocumentoEni", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.VisualizarDocumentoEni")
    @WebMethod(action = "urn:visualizarDocumentoEni")
    @ResponseWrapper(localName = "visualizarDocumentoEniResponse", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.VisualizarDocumentoEniResponse")
    public es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoResultadoVisualizacionDocumentoInside visualizarDocumentoEni(
        @WebParam(name = "documento", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoDocumentoVisualizacionInside documento
    ) throws InsideWSException;

    @WebResult(name = "documento", targetNamespace = "")
    @RequestWrapper(localName = "convertirDocumentoAEni", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ConvertirDocumentoAEni")
    @WebMethod(action = "urn:convertirDocumentoAEni")
    @ResponseWrapper(localName = "convertirDocumentoAEniResponse", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ConvertirDocumentoAEniResponse")
    public es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.DocumentoEniFileInside convertirDocumentoAEni(
        @WebParam(name = "documento", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoDocumentoConversionInside documento,
        @WebParam(name = "contenido", targetNamespace = "")
        byte[] contenido,
        @WebParam(name = "firmar", targetNamespace = "")
        java.lang.Boolean firmar
    ) throws InsideWSException;

    @WebResult(name = "resultadoValidacion", targetNamespace = "")
    @RequestWrapper(localName = "validarDocumentoEniFile", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ValidarDocumentoEniFile")
    @WebMethod(action = "urn:validarDocumentoEniFile")
    @ResponseWrapper(localName = "validarDocumentoEniFileResponse", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ValidarDocumentoEniFileResponse")
    public es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoResultadoValidacionDocumentoInside validarDocumentoEniFile(
        @WebParam(name = "documento", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoDocumentoValidacionInside documento
    ) throws InsideWSException;

    @WebResult(name = "expediente", targetNamespace = "")
    @RequestWrapper(localName = "convertirExpedienteAEni", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ConvertirExpedienteAEni")
    @WebMethod(action = "urn:convertirExpedienteAEni")
    @ResponseWrapper(localName = "convertirExpedienteAEniResponse", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ConvertirExpedienteAEniResponse")
    public es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ExpedienteEniFileInside convertirExpedienteAEni(
        @WebParam(name = "expediente", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoExpedienteConversionInside expediente,
        @WebParam(name = "contenidoFirma", targetNamespace = "")
        java.lang.String contenidoFirma
    ) throws InsideWSException;

    @WebResult(name = "documento", targetNamespace = "")
    @RequestWrapper(localName = "convertirDocumentoAEniConMAdicionales", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ConvertirDocumentoAEniConMAdicionales")
    @WebMethod(action = "urn:convertirDocumentoAEniConMAdicionales")
    @ResponseWrapper(localName = "convertirDocumentoAEniConMAdicionalesResponse", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ConvertirDocumentoAEniConMAdicionalesResponse")
    public es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.DocumentoEniFileInsideConMAdicionales convertirDocumentoAEniConMAdicionales(
        @WebParam(name = "documento", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoDocumentoConversionInside documento,
        @WebParam(name = "metadatosAdicionales", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoMetadatosAdicionales metadatosAdicionales,
        @WebParam(name = "contenido", targetNamespace = "")
        byte[] contenido,
        @WebParam(name = "firmar", targetNamespace = "")
        java.lang.Boolean firmar
    ) throws InsideWSException;

    @WebResult(name = "expediente", targetNamespace = "")
    @RequestWrapper(localName = "convertirExpedienteAEniConMAdicionales", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ConvertirExpedienteAEniConMAdicionales")
    @WebMethod(action = "urn:convertirExpedienteAEniConMAdicionales")
    @ResponseWrapper(localName = "convertirExpedienteAEniConMAdicionalesResponse", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ConvertirExpedienteAEniConMAdicionalesResponse")
    public es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ExpedienteEniFileInsideConMAdicionales convertirExpedienteAEniConMAdicionales(
        @WebParam(name = "expediente", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoExpedienteConversionInside expediente,
        @WebParam(name = "metadatosAdicionales", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoMetadatosAdicionales metadatosAdicionales,
        @WebParam(name = "contenidoFirma", targetNamespace = "")
        java.lang.String contenidoFirma
    ) throws InsideWSException;

    @WebResult(name = "resultadoValidacion", targetNamespace = "")
    @RequestWrapper(localName = "validarExpedienteEniFile", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ValidarExpedienteEniFile")
    @WebMethod(action = "urn:validarExpedienteEniFile")
    @ResponseWrapper(localName = "validarExpedienteEniFileResponse", targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebServiceFiles", className = "es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.ValidarExpedienteEniFileResponse")
    public es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoResultadoValidacionExpedienteInside validarExpedienteEniFile(
        @WebParam(name = "expediente", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.inside.ginside.webservicefiles.TipoExpedienteValidacionInside expediente
    ) throws InsideWSException;
}
