//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.crue.academic.xsd.language.diplomasupplement;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * URL reference to the image file
 *
 * <p>
 * Java class for AttachedImageURLType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="AttachedImageURLType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{urn:crue:academic:xsd:language:diplomasupplement}PlainTextType"/>
 *         &lt;element name="Mime" type="{urn:crue:academic:xsd:language:diplomasupplement}ImageMimeType"/>
 *         &lt;element name="URL" type="{urn:crue:academic:xsd:language:diplomasupplement}URLType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttachedImageURLType", propOrder = {
    "description",
    "mime",
    "url"
})
public class AttachedImageURLType {

    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Mime", required = true)
    protected ImageMimeType mime;
    @XmlElement(name = "URL", required = true)
    protected String url;

    /**
     * Gets the value of the description property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the mime property.
     *
     * @return possible object is {@link ImageMimeType }
     *
     */
    public ImageMimeType getMime() {
        return mime;
    }

    /**
     * Sets the value of the mime property.
     *
     * @param value allowed object is {@link ImageMimeType }
     *
     */
    public void setMime(ImageMimeType value) {
        this.mime = value;
    }

    /**
     * Gets the value of the url property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setURL(String value) {
        this.url = value;
    }

}
