//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.crue.academic.xsd.language.diplomasupplement;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CountryType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * <
 * pre>
 * &lt;simpleType name="CountryType"> &lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"> &lt;enumeration value="AD"/>
 * &lt;enumeration value="AE"/> &lt;enumeration value="AF"/> &lt;enumeration
 * value="AG"/> &lt;enumeration value="AL"/> &lt;enumeration value="AM"/>
 * &lt;enumeration value="AO"/> &lt;enumeration value="AR"/> &lt;enumeration
 * value="AT"/> &lt;enumeration value="AU"/> &lt;enumeration value="AZ"/>
 * &lt;enumeration value="BA"/> &lt;enumeration value="BB"/> &lt;enumeration
 * value="BD"/> &lt;enumeration value="BE"/> &lt;enumeration value="BF"/>
 * &lt;enumeration value="BG"/> &lt;enumeration value="BH"/> &lt;enumeration
 * value="BI"/> &lt;enumeration value="BJ"/> &lt;enumeration value="BN"/>
 * &lt;enumeration value="BO"/> &lt;enumeration value="BR"/> &lt;enumeration
 * value="BS"/> &lt;enumeration value="BT"/> &lt;enumeration value="BW"/>
 * &lt;enumeration value="BY"/> &lt;enumeration value="BZ"/> &lt;enumeration
 * value="CA"/> &lt;enumeration value="CD"/> &lt;enumeration value="CF"/>
 * &lt;enumeration value="CG"/> &lt;enumeration value="CH"/> &lt;enumeration
 * value="CI"/> &lt;enumeration value="CL"/> &lt;enumeration value="CM"/>
 * &lt;enumeration value="CN"/> &lt;enumeration value="CO"/> &lt;enumeration
 * value="CR"/> &lt;enumeration value="CU"/> &lt;enumeration value="CV"/>
 * &lt;enumeration value="CY"/> &lt;enumeration value="CZ"/> &lt;enumeration
 * value="DE"/> &lt;enumeration value="DJ"/> &lt;enumeration value="DK"/>
 * &lt;enumeration value="DM"/> &lt;enumeration value="DO"/> &lt;enumeration
 * value="DZ"/> &lt;enumeration value="EC"/> &lt;enumeration value="EE"/>
 * &lt;enumeration value="EG"/> &lt;enumeration value="ER"/> &lt;enumeration
 * value="ES"/> &lt;enumeration value="ET"/> &lt;enumeration value="FI"/>
 * &lt;enumeration value="FJ"/> &lt;enumeration value="FM"/> &lt;enumeration
 * value="FR"/> &lt;enumeration value="GA"/> &lt;enumeration value="GB"/>
 * &lt;enumeration value="GD"/> &lt;enumeration value="GE"/> &lt;enumeration
 * value="GH"/> &lt;enumeration value="GL"/> &lt;enumeration value="GM"/>
 * &lt;enumeration value="GN"/> &lt;enumeration value="GQ"/> &lt;enumeration
 * value="GR"/> &lt;enumeration value="GT"/> &lt;enumeration value="GW"/>
 * &lt;enumeration value="GY"/> &lt;enumeration value="HN"/> &lt;enumeration
 * value="HR"/> &lt;enumeration value="HT"/> &lt;enumeration value="HU"/>
 * &lt;enumeration value="ID"/> &lt;enumeration value="IE"/> &lt;enumeration
 * value="IL"/> &lt;enumeration value="IN"/> &lt;enumeration value="IQ"/>
 * &lt;enumeration value="IR"/> &lt;enumeration value="IS"/> &lt;enumeration
 * value="IT"/> &lt;enumeration value="JM"/> &lt;enumeration value="JO"/>
 * &lt;enumeration value="JP"/> &lt;enumeration value="KE"/> &lt;enumeration
 * value="KG"/> &lt;enumeration value="KH"/> &lt;enumeration value="KI"/>
 * &lt;enumeration value="KM"/> &lt;enumeration value="KN"/> &lt;enumeration
 * value="KP"/> &lt;enumeration value="KR"/> &lt;enumeration value="KW"/>
 * &lt;enumeration value="KZ"/> &lt;enumeration value="LA"/> &lt;enumeration
 * value="LB"/> &lt;enumeration value="LC"/> &lt;enumeration value="LI"/>
 * &lt;enumeration value="LK"/> &lt;enumeration value="LR"/> &lt;enumeration
 * value="LS"/> &lt;enumeration value="LT"/> &lt;enumeration value="LU"/>
 * &lt;enumeration value="LV"/> &lt;enumeration value="LY"/> &lt;enumeration
 * value="MA"/> &lt;enumeration value="MC"/> &lt;enumeration value="MD"/>
 * &lt;enumeration value="ME"/> &lt;enumeration value="MG"/> &lt;enumeration
 * value="MH"/> &lt;enumeration value="MK"/> &lt;enumeration value="ML"/>
 * &lt;enumeration value="MM"/> &lt;enumeration value="MN"/> &lt;enumeration
 * value="MR"/> &lt;enumeration value="MT"/> &lt;enumeration value="MU"/>
 * &lt;enumeration value="MV"/> &lt;enumeration value="MW"/> &lt;enumeration
 * value="MX"/> &lt;enumeration value="MY"/> &lt;enumeration value="MZ"/>
 * &lt;enumeration value="NA"/> &lt;enumeration value="NE"/> &lt;enumeration
 * value="NG"/> &lt;enumeration value="NI"/> &lt;enumeration value="NL"/>
 * &lt;enumeration value="NO"/> &lt;enumeration value="NP"/> &lt;enumeration
 * value="NR"/> &lt;enumeration value="NU"/> &lt;enumeration value="NZ"/>
 * &lt;enumeration value="OM"/> &lt;enumeration value="PA"/> &lt;enumeration
 * value="PE"/> &lt;enumeration value="PG"/> &lt;enumeration value="PH"/>
 * &lt;enumeration value="PK"/> &lt;enumeration value="PL"/> &lt;enumeration
 * value="PR"/> &lt;enumeration value="PS"/> &lt;enumeration value="PT"/>
 * &lt;enumeration value="PW"/> &lt;enumeration value="PY"/> &lt;enumeration
 * value="QA"/> &lt;enumeration value="RO"/> &lt;enumeration value="RS"/>
 * &lt;enumeration value="RU"/> &lt;enumeration value="RW"/> &lt;enumeration
 * value="SA"/> &lt;enumeration value="SB"/> &lt;enumeration value="SC"/>
 * &lt;enumeration value="SD"/> &lt;enumeration value="SE"/> &lt;enumeration
 * value="SG"/> &lt;enumeration value="SI"/> &lt;enumeration value="SK"/>
 * &lt;enumeration value="SL"/> &lt;enumeration value="SM"/> &lt;enumeration
 * value="SN"/> &lt;enumeration value="SO"/> &lt;enumeration value="SR"/>
 * &lt;enumeration value="ST"/> &lt;enumeration value="SV"/> &lt;enumeration
 * value="SY"/> &lt;enumeration value="SZ"/> &lt;enumeration value="TD"/>
 * &lt;enumeration value="TG"/> &lt;enumeration value="TH"/> &lt;enumeration
 * value="TJ"/> &lt;enumeration value="TL"/> &lt;enumeration value="TM"/>
 * &lt;enumeration value="TN"/> &lt;enumeration value="TO"/> &lt;enumeration
 * value="TR"/> &lt;enumeration value="TT"/> &lt;enumeration value="TV"/>
 * &lt;enumeration value="TZ"/> &lt;enumeration value="UA"/> &lt;enumeration
 * value="UG"/> &lt;enumeration value="US"/> &lt;enumeration value="UY"/>
 * &lt;enumeration value="UZ"/> &lt;enumeration value="VA"/> &lt;enumeration
 * value="VC"/> &lt;enumeration value="VE"/> &lt;enumeration value="VN"/>
 * &lt;enumeration value="VU"/> &lt;enumeration value="WS"/> &lt;enumeration
 * value="YE"/> &lt;enumeration value="ZA"/> &lt;enumeration value="ZM"/>
 * &lt;enumeration value="ZW"/> &lt;/restriction> &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "CountryType")
@XmlEnum
public enum CountryType {

    /**
     * Andorra
     *
     */
    AD,
    /**
     * United Arab Emirates
     *
     */
    AE,
    /**
     * Afghanistan
     *
     */
    AF,
    /**
     * Antigua and Barbuda
     *
     */
    AG,
    /**
     * Albania
     *
     */
    AL,
    /**
     * Armenia
     *
     */
    AM,
    /**
     * Angola
     *
     */
    AO,
    /**
     * Argentina
     *
     */
    AR,
    /**
     * Austria
     *
     */
    AT,
    /**
     * Australia
     *
     */
    AU,
    /**
     * Azerbaijan
     *
     */
    AZ,
    /**
     * Bosnia and Herzegovina
     *
     */
    BA,
    /**
     * Barbados
     *
     */
    BB,
    /**
     * Bangladesh
     *
     */
    BD,
    /**
     * Belgium
     *
     */
    BE,
    /**
     * Burkina Faso
     *
     */
    BF,
    /**
     * Bulgaria
     *
     */
    BG,
    /**
     * Bahrain
     *
     */
    BH,
    /**
     * Burundi
     *
     */
    BI,
    /**
     * Benin
     *
     */
    BJ,
    /**
     * Brunei Darussalam
     *
     */
    BN,
    /**
     * Bolivia
     *
     */
    BO,
    /**
     * Brazil
     *
     */
    BR,
    /**
     * Bahamas
     *
     */
    BS,
    /**
     * Bhutan
     *
     */
    BT,
    /**
     * Botswana
     *
     */
    BW,
    /**
     * Belarus
     *
     */
    BY,
    /**
     * Belize
     *
     */
    BZ,
    /**
     * Canada
     *
     */
    CA,
    /**
     * Congo, Democratic Republic of the
     *
     */
    CD,
    /**
     * Central African Republic
     *
     */
    CF,
    /**
     * Congo, Republic of the
     *
     */
    CG,
    /**
     * Switzerland
     *
     */
    CH,
    /**
     * Cote d/Ivoire
     *
     */
    CI,
    /**
     * Chile
     *
     */
    CL,
    /**
     * Cameroon
     *
     */
    CM,
    /**
     * China
     *
     */
    CN,
    /**
     * Colombia
     *
     */
    CO,
    /**
     * Costa Rica
     *
     */
    CR,
    /**
     * Cuba
     *
     */
    CU,
    /**
     * Cape Verde
     *
     */
    CV,
    /**
     * Cyprus
     *
     */
    CY,
    /**
     * Czech Republic
     *
     */
    CZ,
    /**
     * Germany
     *
     */
    DE,
    /**
     * Djibouti
     *
     */
    DJ,
    /**
     * Denmark
     *
     */
    DK,
    /**
     * Dominica
     *
     */
    DM,
    /**
     * Dominican Republic
     *
     */
    DO,
    /**
     * Algeria
     *
     */
    DZ,
    /**
     * Ecuador
     *
     */
    EC,
    /**
     * Estonia
     *
     */
    EE,
    /**
     * Egypt
     *
     */
    EG,
    /**
     * Eritrea
     *
     */
    ER,
    /**
     * Spain
     *
     */
    ES,
    /**
     * Ethiopia
     *
     */
    ET,
    /**
     * Finland
     *
     */
    FI,
    /**
     * Fiji
     *
     */
    FJ,
    /**
     * Federated States of Micronesia
     *
     */
    FM,
    /**
     * France
     *
     */
    FR,
    /**
     * Gabon
     *
     */
    GA,
    /**
     * United Kingdom
     *
     */
    GB,
    /**
     * Grenada
     *
     */
    GD,
    /**
     * Georgia
     *
     */
    GE,
    /**
     * Ghana
     *
     */
    GH,
    /**
     * Greenland
     *
     */
    GL,
    /**
     * Gambia
     *
     */
    GM,
    /**
     * Guinea
     *
     */
    GN,
    /**
     * Equatorial Guinea
     *
     */
    GQ,
    /**
     * Greece
     *
     */
    GR,
    /**
     * Guatemala
     *
     */
    GT,
    /**
     * Guinea-Bissau
     *
     */
    GW,
    /**
     * Guyana
     *
     */
    GY,
    /**
     * Honduras
     *
     */
    HN,
    /**
     * Croatia
     *
     */
    HR,
    /**
     * Haiti
     *
     */
    HT,
    /**
     * Hungary
     *
     */
    HU,
    /**
     * Indonesia
     *
     */
    ID,
    /**
     * Ireland
     *
     */
    IE,
    /**
     * Israel
     *
     */
    IL,
    /**
     * India
     *
     */
    IN,
    /**
     * Iraq
     *
     */
    IQ,
    /**
     * Iran
     *
     */
    IR,
    /**
     * Iceland
     *
     */
    IS,
    /**
     * Italy
     *
     */
    IT,
    /**
     * Jamaica
     *
     */
    JM,
    /**
     * Jordan
     *
     */
    JO,
    /**
     * Japan
     *
     */
    JP,
    /**
     * Kenya
     *
     */
    KE,
    /**
     * Kyrgyzstan
     *
     */
    KG,
    /**
     * Cambodia
     *
     */
    KH,
    /**
     * Kiribati
     *
     */
    KI,
    /**
     * Comoros
     *
     */
    KM,
    /**
     * Saint Kitts and Nevis
     *
     */
    KN,
    /**
     * Korea, Democratic People/s Republic
     *
     */
    KP,
    /**
     * Korea, Republic of
     *
     */
    KR,
    /**
     * Kuwait
     *
     */
    KW,
    /**
     * Kazakstan
     *
     */
    KZ,
    /**
     * Lao People/s Democratic Republic
     *
     */
    LA,
    /**
     * Lebanon
     *
     */
    LB,
    /**
     * Saint Lucia
     *
     */
    LC,
    /**
     * Liechtenstein
     *
     */
    LI,
    /**
     * Sri Lanka
     *
     */
    LK,
    /**
     * Liberia
     *
     */
    LR,
    /**
     * Lesotho
     *
     */
    LS,
    /**
     * Lithuania
     *
     */
    LT,
    /**
     * Luxembourg
     *
     */
    LU,
    /**
     * Latvia
     *
     */
    LV,
    /**
     * Libyan Arab Jamahiriya
     *
     */
    LY,
    /**
     * Morocco
     *
     */
    MA,
    /**
     * Monaco
     *
     */
    MC,
    /**
     * Moldova, Republic of
     *
     */
    MD,
    /**
     * Montenegro
     *
     */
    ME,
    /**
     * Madagascar
     *
     */
    MG,
    /**
     * Marshall Islands
     *
     */
    MH,
    /**
     * Macedonia, the former Yugoslav Republic of
     *
     */
    MK,
    /**
     * Mali
     *
     */
    ML,
    /**
     * Myanmar
     *
     */
    MM,
    /**
     * Mongolia
     *
     */
    MN,
    /**
     * Mauritania
     *
     */
    MR,
    /**
     * Malta
     *
     */
    MT,
    /**
     * Mauritius
     *
     */
    MU,
    /**
     * Maldives
     *
     */
    MV,
    /**
     * Malawi
     *
     */
    MW,
    /**
     * Mexico
     *
     */
    MX,
    /**
     * Malaysia
     *
     */
    MY,
    /**
     * Mozambique
     *
     */
    MZ,
    /**
     * Namibia
     *
     */
    NA,
    /**
     * Niger
     *
     */
    NE,
    /**
     * Nigeria
     *
     */
    NG,
    /**
     * Nicaragua
     *
     */
    NI,
    /**
     * Netherlands
     *
     */
    NL,
    /**
     * Norway
     *
     */
    NO,
    /**
     * Nepal
     *
     */
    NP,
    /**
     * Nauru
     *
     */
    NR,
    /**
     * Niue
     *
     */
    NU,
    /**
     * New Zealand
     *
     */
    NZ,
    /**
     * Oman
     *
     */
    OM,
    /**
     * Panama
     *
     */
    PA,
    /**
     * Peru
     *
     */
    PE,
    /**
     * Papua New Guinea
     *
     */
    PG,
    /**
     * Philippines
     *
     */
    PH,
    /**
     * Pakistan
     *
     */
    PK,
    /**
     * Poland
     *
     */
    PL,
    /**
     * Puerto Rico
     *
     */
    PR,
    /**
     * Palestinian Territory, Occupied
     *
     */
    PS,
    /**
     * Portugal
     *
     */
    PT,
    /**
     * Palau
     *
     */
    PW,
    /**
     * Paraguay
     *
     */
    PY,
    /**
     * Qatar
     *
     */
    QA,
    /**
     * Romania
     *
     */
    RO,
    /**
     * Serbia
     *
     */
    RS,
    /**
     * Russian Federation
     *
     */
    RU,
    /**
     * Rwanda
     *
     */
    RW,
    /**
     * Saudi Arabia
     *
     */
    SA,
    /**
     * Solomon Islands
     *
     */
    SB,
    /**
     * Seychelles
     *
     */
    SC,
    /**
     * Sudan
     *
     */
    SD,
    /**
     * Sweden
     *
     */
    SE,
    /**
     * Singapore
     *
     */
    SG,
    /**
     * Slovenia
     *
     */
    SI,
    /**
     * Slovakia
     *
     */
    SK,
    /**
     * Sierra Leone
     *
     */
    SL,
    /**
     * San Marino
     *
     */
    SM,
    /**
     * Senegal
     *
     */
    SN,
    /**
     * Somalia
     *
     */
    SO,
    /**
     * Suriname
     *
     */
    SR,
    /**
     * Sao Tome and Principe
     *
     */
    ST,
    /**
     * El Salvador
     *
     */
    SV,
    /**
     * Syrian Arab Republic
     *
     */
    SY,
    /**
     * Swaziland
     *
     */
    SZ,
    /**
     * Chad
     *
     */
    TD,
    /**
     * Togo
     *
     */
    TG,
    /**
     * Thailand
     *
     */
    TH,
    /**
     * Tajikistan
     *
     */
    TJ,
    /**
     * Timor-Leste
     *
     */
    TL,
    /**
     * Turkmenistan
     *
     */
    TM,
    /**
     * Tunisia
     *
     */
    TN,
    /**
     * Tonga
     *
     */
    TO,
    /**
     * Turkey
     *
     */
    TR,
    /**
     * Trindidad and Tobago
     *
     */
    TT,
    /**
     * Tuvalu
     *
     */
    TV,
    /**
     * Tanzania, United republic of
     *
     */
    TZ,
    /**
     * Ukraina
     *
     */
    UA,
    /**
     * Uganda
     *
     */
    UG,
    /**
     * United States
     *
     */
    US,
    /**
     * Uruguay
     *
     */
    UY,
    /**
     * Uzbekistan
     *
     */
    UZ,
    /**
     * Holy See (Vatican City State)
     *
     */
    VA,
    /**
     * Saint Vincent and the Granadines
     *
     */
    VC,
    /**
     * Venezuela
     *
     */
    VE,
    /**
     * Viet Nam
     *
     */
    VN,
    /**
     * Vanuatu
     *
     */
    VU,
    /**
     * Samoa
     *
     */
    WS,
    /**
     * Yemen
     *
     */
    YE,
    /**
     * South Africa
     *
     */
    ZA,
    /**
     * Zambia
     *
     */
    ZM,
    /**
     * Zimbabwe
     *
     */
    ZW;

    public String value() {
        return name();
    }

    public static CountryType fromValue(String v) {
        return valueOf(v);
    }

}
