//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.crue.academic.xsd.language.diplomasupplement;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * Name and status of the institution
 *
 * <p>
 * Java class for InstitutionType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="InstitutionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{urn:crue:academic:xsd:language:diplomasupplement}PlainTextType"/>
 *         &lt;element name="Status" type="{urn:crue:academic:xsd:language:diplomasupplement}PlainTextType"/>
 *         &lt;element name="Country">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;urn:crue:academic:xsd:language:diplomasupplement>PlainTextType">
 *                 &lt;attribute name="country" use="required" type="{urn:crue:academic:xsd:language:diplomasupplement}CountryType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AdditionalInformation" type="{urn:crue:academic:xsd:language:diplomasupplement}RichTextTagType" minOccurs="0"/>
 *         &lt;element name="ContactInformation" type="{urn:crue:academic:xsd:language:diplomasupplement}ContactInformationType" minOccurs="0"/>
 *         &lt;element name="AttachedImageRef" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;urn:crue:academic:xsd:language:diplomasupplement>PlainTextType">
 *                 &lt;attribute name="attachedID" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="nationalID" type="{urn:crue:academic:xsd:language:diplomasupplement}PlainTextType" />
 *       &lt;attribute name="erasmusID" type="{urn:crue:academic:xsd:language:diplomasupplement}PlainTextType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstitutionType", propOrder = {
    "name",
    "status",
    "country",
    "additionalInformation",
    "contactInformation",
    "attachedImageRef"
})
@XmlSeeAlso({
    eu.stork.peps.complex.attributes.crue.academic.xsd.language.diplomasupplement.NameAndStatusOfAwardingInstitutionType.AwardingInstitution.class,
    eu.stork.peps.complex.attributes.crue.academic.xsd.language.diplomasupplement.NameAndStatusOfInstitutionAdministeringStudiesType.InstitutionAdministeringStudies.class
})
public class InstitutionType {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "Country", required = true)
    protected InstitutionType.Country country;
    @XmlElement(name = "AdditionalInformation")
    protected RichTextTagType additionalInformation;
    @XmlElement(name = "ContactInformation")
    protected ContactInformationType contactInformation;
    @XmlElement(name = "AttachedImageRef")
    protected InstitutionType.AttachedImageRef attachedImageRef;
    @XmlAttribute(name = "nationalID")
    protected String nationalID;
    @XmlAttribute(name = "erasmusID")
    protected String erasmusID;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the country property.
     *
     * @return possible object is {@link InstitutionType.Country }
     *
     */
    public InstitutionType.Country getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     *
     * @param value allowed object is {@link InstitutionType.Country }
     *
     */
    public void setCountry(InstitutionType.Country value) {
        this.country = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getAdditionalInformation() {
        return additionalInformation;
    }

    /**
     * Sets the value of the additionalInformation property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setAdditionalInformation(RichTextTagType value) {
        this.additionalInformation = value;
    }

    /**
     * Gets the value of the contactInformation property.
     *
     * @return possible object is {@link ContactInformationType }
     *
     */
    public ContactInformationType getContactInformation() {
        return contactInformation;
    }

    /**
     * Sets the value of the contactInformation property.
     *
     * @param value allowed object is {@link ContactInformationType }
     *
     */
    public void setContactInformation(ContactInformationType value) {
        this.contactInformation = value;
    }

    /**
     * Gets the value of the attachedImageRef property.
     *
     * @return possible object is {@link InstitutionType.AttachedImageRef }
     *
     */
    public InstitutionType.AttachedImageRef getAttachedImageRef() {
        return attachedImageRef;
    }

    /**
     * Sets the value of the attachedImageRef property.
     *
     * @param value allowed object is {@link InstitutionType.AttachedImageRef }
     *
     */
    public void setAttachedImageRef(InstitutionType.AttachedImageRef value) {
        this.attachedImageRef = value;
    }

    /**
     * Gets the value of the nationalID property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNationalID() {
        return nationalID;
    }

    /**
     * Sets the value of the nationalID property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNationalID(String value) {
        this.nationalID = value;
    }

    /**
     * Gets the value of the erasmusID property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getErasmusID() {
        return erasmusID;
    }

    /**
     * Sets the value of the erasmusID property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setErasmusID(String value) {
        this.erasmusID = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:crue:academic:xsd:language:diplomasupplement>PlainTextType">
     *       &lt;attribute name="attachedID" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class AttachedImageRef {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "attachedID", required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object attachedID;

        /**
         * Plain text constraint
         *
         * Non empty text
         *
         * @return possible object is {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the attachedID property.
         *
         * @return possible object is {@link Object }
         *
         */
        public Object getAttachedID() {
            return attachedID;
        }

        /**
         * Sets the value of the attachedID property.
         *
         * @param value allowed object is {@link Object }
         *
         */
        public void setAttachedID(Object value) {
            this.attachedID = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:crue:academic:xsd:language:diplomasupplement>PlainTextType">
     *       &lt;attribute name="country" use="required" type="{urn:crue:academic:xsd:language:diplomasupplement}CountryType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Country {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "country", required = true)
        protected CountryType country;

        /**
         * Plain text constraint
         *
         * Non empty text
         *
         * @return possible object is {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the country property.
         *
         * @return possible object is {@link CountryType }
         *
         */
        public CountryType getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         *
         * @param value allowed object is {@link CountryType }
         *
         */
        public void setCountry(CountryType value) {
            this.country = value;
        }

    }

}
