//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.crue.academic.xsd.language.diplomasupplement;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for MimeType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * <
 * pre>
 * &lt;simpleType name="MimeType"> &lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"> &lt;enumeration
 * value="image/gif"/> &lt;enumeration value="image/jpeg"/> &lt;enumeration
 * value="image/pjpeg"/> &lt;enumeration value="image/png"/> &lt;enumeration
 * value="image/tiff"/> &lt;enumeration value="text/html"/> &lt;enumeration
 * value="application/pdf"/> &lt;/restriction> &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "MimeType")
@XmlEnum
public enum MimeType {

    /**
     * GIF image
     *
     */
    @XmlEnumValue("image/gif")
    IMAGE_GIF("image/gif"),
    /**
     * JPEG JFIF image
     *
     */
    @XmlEnumValue("image/jpeg")
    IMAGE_JPEG("image/jpeg"),
    /**
     * JPEG JFIF image
     *
     */
    @XmlEnumValue("image/pjpeg")
    IMAGE_PJPEG("image/pjpeg"),
    /**
     * Portable Network Graphics
     *
     */
    @XmlEnumValue("image/png")
    IMAGE_PNG("image/png"),
    /**
     * Tag Image File Format
     *
     */
    @XmlEnumValue("image/tiff")
    IMAGE_TIFF("image/tiff"),
    /**
     * HTML
     *
     */
    @XmlEnumValue("text/html")
    TEXT_HTML("text/html"),
    /**
     * Portable Document Format
     *
     */
    @XmlEnumValue("application/pdf")
    APPLICATION_PDF("application/pdf");
    private final String value;

    MimeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MimeType fromValue(String v) {
        for (MimeType c : MimeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
