//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.crue.academic.xsd.language.diplomasupplement;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * Mobility programme course unit
 *
 * <p>
 * Java class for MobilityProgrammeCourseUnitType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="MobilityProgrammeCourseUnitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Code" type="{urn:crue:academic:xsd:language:diplomasupplement}PlainTextType" minOccurs="0"/>
 *         &lt;element name="Title">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;urn:crue:academic:xsd:language:diplomasupplement>PlainTextType">
 *                 &lt;attribute name="language" type="{urn:crue:academic:xsd:language:diplomasupplement}LanguageType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ECTSCredits" type="{urn:crue:academic:xsd:language:diplomasupplement}PositiveDecimalType" minOccurs="0"/>
 *         &lt;element name="AdditionalInformation" type="{urn:crue:academic:xsd:language:diplomasupplement}RichTextTagType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isInTheLearningAgreement" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MobilityProgrammeCourseUnitType", propOrder = {
    "code",
    "title",
    "ectsCredits",
    "additionalInformation"
})
public class MobilityProgrammeCourseUnitType {

    @XmlElement(name = "Code")
    protected String code;
    @XmlElement(name = "Title", required = true)
    protected MobilityProgrammeCourseUnitType.Title title;
    @XmlElement(name = "ECTSCredits")
    protected BigDecimal ectsCredits;
    @XmlElement(name = "AdditionalInformation")
    protected RichTextTagType additionalInformation;
    @XmlAttribute(name = "isInTheLearningAgreement")
    protected Boolean isInTheLearningAgreement;

    /**
     * Gets the value of the code property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the title property.
     *
     * @return possible object is {@link MobilityProgrammeCourseUnitType.Title }
     *
     */
    public MobilityProgrammeCourseUnitType.Title getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value allowed object is
     *     {@link MobilityProgrammeCourseUnitType.Title }
     *
     */
    public void setTitle(MobilityProgrammeCourseUnitType.Title value) {
        this.title = value;
    }

    /**
     * Gets the value of the ectsCredits property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getECTSCredits() {
        return ectsCredits;
    }

    /**
     * Sets the value of the ectsCredits property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setECTSCredits(BigDecimal value) {
        this.ectsCredits = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getAdditionalInformation() {
        return additionalInformation;
    }

    /**
     * Sets the value of the additionalInformation property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setAdditionalInformation(RichTextTagType value) {
        this.additionalInformation = value;
    }

    /**
     * Gets the value of the isInTheLearningAgreement property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public boolean isIsInTheLearningAgreement() {
        if (isInTheLearningAgreement == null) {
            return true;
        } else {
            return isInTheLearningAgreement;
        }
    }

    /**
     * Sets the value of the isInTheLearningAgreement property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setIsInTheLearningAgreement(Boolean value) {
        this.isInTheLearningAgreement = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:crue:academic:xsd:language:diplomasupplement>PlainTextType">
     *       &lt;attribute name="language" type="{urn:crue:academic:xsd:language:diplomasupplement}LanguageType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Title {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "language")
        protected LanguageType language;

        /**
         * Plain text constraint
         *
         * Non empty text
         *
         * @return possible object is {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the language property.
         *
         * @return possible object is {@link LanguageType }
         *
         */
        public LanguageType getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         *
         * @param value allowed object is {@link LanguageType }
         *
         */
        public void setLanguage(LanguageType value) {
            this.language = value;
        }

    }

}
