//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.crue.academic.xsd.language.diplomasupplement;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Mobility programme courses units
 *
 * <p>
 * Java class for MobilityProgrammeCoursesUnitsType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="MobilityProgrammeCoursesUnitsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CourseUnit" type="{urn:crue:academic:xsd:language:diplomasupplement}MobilityProgrammeCourseUnitType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MobilityProgrammeCoursesUnitsType", propOrder = {
    "courseUnit"
})
public class MobilityProgrammeCoursesUnitsType {

    @XmlElement(name = "CourseUnit", required = true)
    protected List<MobilityProgrammeCourseUnitType> courseUnit;

    /**
     * Gets the value of the courseUnit property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the courseUnit property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCourseUnit().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MobilityProgrammeCourseUnitType }
     *
     *
     */
    public List<MobilityProgrammeCourseUnitType> getCourseUnit() {
        if (courseUnit == null) {
            courseUnit = new ArrayList<MobilityProgrammeCourseUnitType>();
        }
        return this.courseUnit;
    }

}
