//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.crue.academic.xsd.language.diplomasupplement;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Name and status of institution administering studies
 *
 * <p>
 * Java class for NameAndStatusOfInstitutionAdministeringStudiesType complex
 * type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="NameAndStatusOfInstitutionAdministeringStudiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InstitutionAdministeringStudies" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{urn:crue:academic:xsd:language:diplomasupplement}InstitutionType">
 *                 &lt;attribute name="institutionAdministeringStudiesID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NameAndStatusOfInstitutionAdministeringStudiesType", propOrder = {
    "institutionAdministeringStudies"
})
public class NameAndStatusOfInstitutionAdministeringStudiesType {

    @XmlElement(name = "InstitutionAdministeringStudies", required = true)
    protected List<NameAndStatusOfInstitutionAdministeringStudiesType.InstitutionAdministeringStudies> institutionAdministeringStudies;

    /**
     * Gets the value of the institutionAdministeringStudies property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the institutionAdministeringStudies property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstitutionAdministeringStudies().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameAndStatusOfInstitutionAdministeringStudiesType.InstitutionAdministeringStudies }
     *
     *
     */
    public List<NameAndStatusOfInstitutionAdministeringStudiesType.InstitutionAdministeringStudies> getInstitutionAdministeringStudies() {
        if (institutionAdministeringStudies == null) {
            institutionAdministeringStudies = new ArrayList<NameAndStatusOfInstitutionAdministeringStudiesType.InstitutionAdministeringStudies>();
        }
        return this.institutionAdministeringStudies;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{urn:crue:academic:xsd:language:diplomasupplement}InstitutionType">
     *       &lt;attribute name="institutionAdministeringStudiesID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class InstitutionAdministeringStudies
            extends InstitutionType {

        @XmlAttribute(name = "institutionAdministeringStudiesID", required = true)
        protected String institutionAdministeringStudiesID;

        /**
         * Gets the value of the institutionAdministeringStudiesID property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getInstitutionAdministeringStudiesID() {
            return institutionAdministeringStudiesID;
        }

        /**
         * Sets the value of the institutionAdministeringStudiesID property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setInstitutionAdministeringStudiesID(String value) {
            this.institutionAdministeringStudiesID = value;
        }

    }

}
