//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.crue.academic.xsd.language.diplomasupplement;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * crue.academic.xsd.language.diplomasupplement package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MultilingualDiplomaSupplement_QNAME = new QName("urn:crue:academic:xsd:language:diplomasupplement", "MultilingualDiplomaSupplement");
    private final static QName _DiplomaSupplement_QNAME = new QName("urn:crue:academic:xsd:language:diplomasupplement", "DiplomaSupplement");
    private final static QName _RichTextTagTypeItalic_QNAME = new QName("urn:crue:academic:xsd:language:diplomasupplement", "Italic");
    private final static QName _RichTextTagTypeBreakLine_QNAME = new QName("urn:crue:academic:xsd:language:diplomasupplement", "BreakLine");
    private final static QName _RichTextTagTypeAttachedRef_QNAME = new QName("urn:crue:academic:xsd:language:diplomasupplement", "AttachedRef");
    private final static QName _RichTextTagTypeUnderline_QNAME = new QName("urn:crue:academic:xsd:language:diplomasupplement", "Underline");
    private final static QName _RichTextTagTypeBold_QNAME = new QName("urn:crue:academic:xsd:language:diplomasupplement", "Bold");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package:
     * crue.academic.xsd.language.diplomasupplement
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressType }
     *
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link LanguagesOfInstructionAndExaminationType }
     *
     */
    public LanguagesOfInstructionAndExaminationType createLanguagesOfInstructionAndExaminationType() {
        return new LanguagesOfInstructionAndExaminationType();
    }

    /**
     * Create an instance of {@link RichTextTagType }
     *
     */
    public RichTextTagType createRichTextTagType() {
        return new RichTextTagType();
    }

    /**
     * Create an instance of {@link MobilityProgrammeType }
     *
     */
    public MobilityProgrammeType createMobilityProgrammeType() {
        return new MobilityProgrammeType();
    }

    /**
     * Create an instance of {@link NameAndStatusOfInstitutionAdministeringStudiesType
     * }
     *
     */
    public NameAndStatusOfInstitutionAdministeringStudiesType createNameAndStatusOfInstitutionAdministeringStudiesType() {
        return new NameAndStatusOfInstitutionAdministeringStudiesType();
    }

    /**
     * Create an instance of {@link InstitutionType }
     *
     */
    public InstitutionType createInstitutionType() {
        return new InstitutionType();
    }

    /**
     * Create an instance of {@link MobilityProgrammeCourseUnitType }
     *
     */
    public MobilityProgrammeCourseUnitType createMobilityProgrammeCourseUnitType() {
        return new MobilityProgrammeCourseUnitType();
    }

    /**
     * Create an instance of {@link InformationIdentifyingTheHolderOfTheQualificationType
     * }
     *
     */
    public InformationIdentifyingTheHolderOfTheQualificationType createInformationIdentifyingTheHolderOfTheQualificationType() {
        return new InformationIdentifyingTheHolderOfTheQualificationType();
    }

    /**
     * Create an instance of {@link CourseUnitType }
     *
     */
    public CourseUnitType createCourseUnitType() {
        return new CourseUnitType();
    }

    /**
     * Create an instance of {@link LocalGradeType }
     *
     */
    public LocalGradeType createLocalGradeType() {
        return new LocalGradeType();
    }

    /**
     * Create an instance of {@link InformationOnTheContentsAndResultsGainedType
     * }
     *
     */
    public InformationOnTheContentsAndResultsGainedType createInformationOnTheContentsAndResultsGainedType() {
        return new InformationOnTheContentsAndResultsGainedType();
    }

    /**
     * Create an instance of {@link InformationOnTheLevelOfTheQualificationType
     * }
     *
     */
    public InformationOnTheLevelOfTheQualificationType createInformationOnTheLevelOfTheQualificationType() {
        return new InformationOnTheLevelOfTheQualificationType();
    }

    /**
     * Create an instance of {@link NameAndStatusOfAwardingInstitutionType }
     *
     */
    public NameAndStatusOfAwardingInstitutionType createNameAndStatusOfAwardingInstitutionType() {
        return new NameAndStatusOfAwardingInstitutionType();
    }

    /**
     * Create an instance of {@link InformationOnTheFunctionOfTheQualificationType
     * }
     *
     */
    public InformationOnTheFunctionOfTheQualificationType createInformationOnTheFunctionOfTheQualificationType() {
        return new InformationOnTheFunctionOfTheQualificationType();
    }

    /**
     * Create an instance of {@link MultilingualDiplomaSupplementType }
     *
     */
    public MultilingualDiplomaSupplementType createMultilingualDiplomaSupplementType() {
        return new MultilingualDiplomaSupplementType();
    }

    /**
     * Create an instance of {@link DiplomaSupplementType }
     *
     */
    public DiplomaSupplementType createDiplomaSupplementType() {
        return new DiplomaSupplementType();
    }

    /**
     * Create an instance of {@link ExtensionContentType }
     *
     */
    public ExtensionContentType createExtensionContentType() {
        return new ExtensionContentType();
    }

    /**
     * Create an instance of {@link AttachedImageURLType }
     *
     */
    public AttachedImageURLType createAttachedImageURLType() {
        return new AttachedImageURLType();
    }

    /**
     * Create an instance of {@link CourseStructureDiagramType }
     *
     */
    public CourseStructureDiagramType createCourseStructureDiagramType() {
        return new CourseStructureDiagramType();
    }

    /**
     * Create an instance of {@link CourseUnitWorkPlacementType }
     *
     */
    public CourseUnitWorkPlacementType createCourseUnitWorkPlacementType() {
        return new CourseUnitWorkPlacementType();
    }

    /**
     * Create an instance of {@link InformationIdentifyingTheQualificationType }
     *
     */
    public InformationIdentifyingTheQualificationType createInformationIdentifyingTheQualificationType() {
        return new InformationIdentifyingTheQualificationType();
    }

    /**
     * Create an instance of {@link MobilityProgrammeCoursesUnitsType }
     *
     */
    public MobilityProgrammeCoursesUnitsType createMobilityProgrammeCoursesUnitsType() {
        return new MobilityProgrammeCoursesUnitsType();
    }

    /**
     * Create an instance of {@link QualificationType }
     *
     */
    public QualificationType createQualificationType() {
        return new QualificationType();
    }

    /**
     * Create an instance of {@link CertificationOfTheSupplementType }
     *
     */
    public CertificationOfTheSupplementType createCertificationOfTheSupplementType() {
        return new CertificationOfTheSupplementType();
    }

    /**
     * Create an instance of {@link AttachedFileURLType }
     *
     */
    public AttachedFileURLType createAttachedFileURLType() {
        return new AttachedFileURLType();
    }

    /**
     * Create an instance of {@link ProgrammeRequirementsType }
     *
     */
    public ProgrammeRequirementsType createProgrammeRequirementsType() {
        return new ProgrammeRequirementsType();
    }

    /**
     * Create an instance of {@link CourseUnitWorkPlacementsType }
     *
     */
    public CourseUnitWorkPlacementsType createCourseUnitWorkPlacementsType() {
        return new CourseUnitWorkPlacementsType();
    }

    /**
     * Create an instance of {@link AdditionalInformationType }
     *
     */
    public AdditionalInformationType createAdditionalInformationType() {
        return new AdditionalInformationType();
    }

    /**
     * Create an instance of {@link GradingSchemeAndGradeDistributionGuidanceType
     * }
     *
     */
    public GradingSchemeAndGradeDistributionGuidanceType createGradingSchemeAndGradeDistributionGuidanceType() {
        return new GradingSchemeAndGradeDistributionGuidanceType();
    }

    /**
     * Create an instance of {@link AttachmentsType }
     *
     */
    public AttachmentsType createAttachmentsType() {
        return new AttachmentsType();
    }

    /**
     * Create an instance of {@link CourseUnitLanguageOfInstructionType }
     *
     */
    public CourseUnitLanguageOfInstructionType createCourseUnitLanguageOfInstructionType() {
        return new CourseUnitLanguageOfInstructionType();
    }

    /**
     * Create an instance of {@link CoursesAttendedInOtherInstitutionInMobilityProgramsType
     * }
     *
     */
    public CoursesAttendedInOtherInstitutionInMobilityProgramsType createCoursesAttendedInOtherInstitutionInMobilityProgramsType() {
        return new CoursesAttendedInOtherInstitutionInMobilityProgramsType();
    }

    /**
     * Create an instance of {@link FamilyNameType }
     *
     */
    public FamilyNameType createFamilyNameType() {
        return new FamilyNameType();
    }

    /**
     * Create an instance of {@link CoursesGroupsType }
     *
     */
    public CoursesGroupsType createCoursesGroupsType() {
        return new CoursesGroupsType();
    }

    /**
     * Create an instance of {@link TitleConferredType }
     *
     */
    public TitleConferredType createTitleConferredType() {
        return new TitleConferredType();
    }

    /**
     * Create an instance of {@link OfficialStampType }
     *
     */
    public OfficialStampType createOfficialStampType() {
        return new OfficialStampType();
    }

    /**
     * Create an instance of {@link CourseUnitStudentPerformanceType }
     *
     */
    public CourseUnitStudentPerformanceType createCourseUnitStudentPerformanceType() {
        return new CourseUnitStudentPerformanceType();
    }

    /**
     * Create an instance of {@link GivenNameType }
     *
     */
    public GivenNameType createGivenNameType() {
        return new GivenNameType();
    }

    /**
     * Create an instance of {@link CoursesUnitsType }
     *
     */
    public CoursesUnitsType createCoursesUnitsType() {
        return new CoursesUnitsType();
    }

    /**
     * Create an instance of {@link ProgrammeDetailsType }
     *
     */
    public ProgrammeDetailsType createProgrammeDetailsType() {
        return new ProgrammeDetailsType();
    }

    /**
     * Create an instance of {@link OfficialCertifyingType }
     *
     */
    public OfficialCertifyingType createOfficialCertifyingType() {
        return new OfficialCertifyingType();
    }

    /**
     * Create an instance of {@link CourseUnitLanguagesOfInstructionType }
     *
     */
    public CourseUnitLanguagesOfInstructionType createCourseUnitLanguagesOfInstructionType() {
        return new CourseUnitLanguagesOfInstructionType();
    }

    /**
     * Create an instance of {@link AttachedImageDataType }
     *
     */
    public AttachedImageDataType createAttachedImageDataType() {
        return new AttachedImageDataType();
    }

    /**
     * Create an instance of {@link AttachedType }
     *
     */
    public AttachedType createAttachedType() {
        return new AttachedType();
    }

    /**
     * Create an instance of {@link CoursesGroupType }
     *
     */
    public CoursesGroupType createCoursesGroupType() {
        return new CoursesGroupType();
    }

    /**
     * Create an instance of {@link AttachedFileDataType }
     *
     */
    public AttachedFileDataType createAttachedFileDataType() {
        return new AttachedFileDataType();
    }

    /**
     * Create an instance of {@link ContactInformationType }
     *
     */
    public ContactInformationType createContactInformationType() {
        return new ContactInformationType();
    }

    /**
     * Create an instance of {@link OfficialsCertifyingType }
     *
     */
    public OfficialsCertifyingType createOfficialsCertifyingType() {
        return new OfficialsCertifyingType();
    }

    /**
     * Create an instance of {@link AddressType.Country }
     *
     */
    public AddressType.Country createAddressTypeCountry() {
        return new AddressType.Country();
    }

    /**
     * Create an instance of {@link LanguagesOfInstructionAndExaminationType.Language
     * }
     *
     */
    public LanguagesOfInstructionAndExaminationType.Language createLanguagesOfInstructionAndExaminationTypeLanguage() {
        return new LanguagesOfInstructionAndExaminationType.Language();
    }

    /**
     * Create an instance of {@link RichTextTagType.AttachedRef }
     *
     */
    public RichTextTagType.AttachedRef createRichTextTagTypeAttachedRef() {
        return new RichTextTagType.AttachedRef();
    }

    /**
     * Create an instance of {@link MobilityProgrammeType.Country }
     *
     */
    public MobilityProgrammeType.Country createMobilityProgrammeTypeCountry() {
        return new MobilityProgrammeType.Country();
    }

    /**
     * Create an instance of {@link NameAndStatusOfInstitutionAdministeringStudiesType.InstitutionAdministeringStudies
     * }
     *
     */
    public NameAndStatusOfInstitutionAdministeringStudiesType.InstitutionAdministeringStudies createNameAndStatusOfInstitutionAdministeringStudiesTypeInstitutionAdministeringStudies() {
        return new NameAndStatusOfInstitutionAdministeringStudiesType.InstitutionAdministeringStudies();
    }

    /**
     * Create an instance of {@link InstitutionType.Country }
     *
     */
    public InstitutionType.Country createInstitutionTypeCountry() {
        return new InstitutionType.Country();
    }

    /**
     * Create an instance of {@link InstitutionType.AttachedImageRef }
     *
     */
    public InstitutionType.AttachedImageRef createInstitutionTypeAttachedImageRef() {
        return new InstitutionType.AttachedImageRef();
    }

    /**
     * Create an instance of {@link MobilityProgrammeCourseUnitType.Title }
     *
     */
    public MobilityProgrammeCourseUnitType.Title createMobilityProgrammeCourseUnitTypeTitle() {
        return new MobilityProgrammeCourseUnitType.Title();
    }

    /**
     * Create an instance of {@link InformationIdentifyingTheHolderOfTheQualificationType.CountryOfBirth
     * }
     *
     */
    public InformationIdentifyingTheHolderOfTheQualificationType.CountryOfBirth createInformationIdentifyingTheHolderOfTheQualificationTypeCountryOfBirth() {
        return new InformationIdentifyingTheHolderOfTheQualificationType.CountryOfBirth();
    }

    /**
     * Create an instance of {@link InformationIdentifyingTheHolderOfTheQualificationType.Gender
     * }
     *
     */
    public InformationIdentifyingTheHolderOfTheQualificationType.Gender createInformationIdentifyingTheHolderOfTheQualificationTypeGender() {
        return new InformationIdentifyingTheHolderOfTheQualificationType.Gender();
    }

    /**
     * Create an instance of {@link CourseUnitType.Type }
     *
     */
    public CourseUnitType.Type createCourseUnitTypeType() {
        return new CourseUnitType.Type();
    }

    /**
     * Create an instance of {@link CourseUnitType.YearOfStudy }
     *
     */
    public CourseUnitType.YearOfStudy createCourseUnitTypeYearOfStudy() {
        return new CourseUnitType.YearOfStudy();
    }

    /**
     * Create an instance of {@link CourseUnitType.Level }
     *
     */
    public CourseUnitType.Level createCourseUnitTypeLevel() {
        return new CourseUnitType.Level();
    }

    /**
     * Create an instance of {@link CourseUnitType.ModeOfDelivery }
     *
     */
    public CourseUnitType.ModeOfDelivery createCourseUnitTypeModeOfDelivery() {
        return new CourseUnitType.ModeOfDelivery();
    }

    /**
     * Create an instance of {@link LocalGradeType.Source }
     *
     */
    public LocalGradeType.Source createLocalGradeTypeSource() {
        return new LocalGradeType.Source();
    }

    /**
     * Create an instance of {@link InformationOnTheContentsAndResultsGainedType.ModeOfStudy
     * }
     *
     */
    public InformationOnTheContentsAndResultsGainedType.ModeOfStudy createInformationOnTheContentsAndResultsGainedTypeModeOfStudy() {
        return new InformationOnTheContentsAndResultsGainedType.ModeOfStudy();
    }

    /**
     * Create an instance of {@link InformationOnTheLevelOfTheQualificationType.Level
     * }
     *
     */
    public InformationOnTheLevelOfTheQualificationType.Level createInformationOnTheLevelOfTheQualificationTypeLevel() {
        return new InformationOnTheLevelOfTheQualificationType.Level();
    }

    /**
     * Create an instance of {@link InformationOnTheLevelOfTheQualificationType.OfficialLengthOfProgramme
     * }
     *
     */
    public InformationOnTheLevelOfTheQualificationType.OfficialLengthOfProgramme createInformationOnTheLevelOfTheQualificationTypeOfficialLengthOfProgramme() {
        return new InformationOnTheLevelOfTheQualificationType.OfficialLengthOfProgramme();
    }

    /**
     * Create an instance of {@link NameAndStatusOfAwardingInstitutionType.AwardingInstitution
     * }
     *
     */
    public NameAndStatusOfAwardingInstitutionType.AwardingInstitution createNameAndStatusOfAwardingInstitutionTypeAwardingInstitution() {
        return new NameAndStatusOfAwardingInstitutionType.AwardingInstitution();
    }

    /**
     * Create an instance of {@link InformationOnTheFunctionOfTheQualificationType.ProfessionalStatus
     * }
     *
     */
    public InformationOnTheFunctionOfTheQualificationType.ProfessionalStatus createInformationOnTheFunctionOfTheQualificationTypeProfessionalStatus() {
        return new InformationOnTheFunctionOfTheQualificationType.ProfessionalStatus();
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link MultilingualDiplomaSupplementType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:crue:academic:xsd:language:diplomasupplement", name = "MultilingualDiplomaSupplement")
    public JAXBElement<MultilingualDiplomaSupplementType> createMultilingualDiplomaSupplement(MultilingualDiplomaSupplementType value) {
        return new JAXBElement<MultilingualDiplomaSupplementType>(_MultilingualDiplomaSupplement_QNAME, MultilingualDiplomaSupplementType.class, null, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link DiplomaSupplementType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:crue:academic:xsd:language:diplomasupplement", name = "DiplomaSupplement")
    public JAXBElement<DiplomaSupplementType> createDiplomaSupplement(DiplomaSupplementType value) {
        return new JAXBElement<DiplomaSupplementType>(_DiplomaSupplement_QNAME, DiplomaSupplementType.class, null, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:crue:academic:xsd:language:diplomasupplement", name = "Italic", scope = RichTextTagType.class)
    public JAXBElement<String> createRichTextTagTypeItalic(String value) {
        return new JAXBElement<String>(_RichTextTagTypeItalic_QNAME, String.class, RichTextTagType.class, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:crue:academic:xsd:language:diplomasupplement", name = "BreakLine", scope = RichTextTagType.class)
    public JAXBElement<String> createRichTextTagTypeBreakLine(String value) {
        return new JAXBElement<String>(_RichTextTagTypeBreakLine_QNAME, String.class, RichTextTagType.class, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link RichTextTagType.AttachedRef }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:crue:academic:xsd:language:diplomasupplement", name = "AttachedRef", scope = RichTextTagType.class)
    public JAXBElement<RichTextTagType.AttachedRef> createRichTextTagTypeAttachedRef(RichTextTagType.AttachedRef value) {
        return new JAXBElement<RichTextTagType.AttachedRef>(_RichTextTagTypeAttachedRef_QNAME, RichTextTagType.AttachedRef.class, RichTextTagType.class, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:crue:academic:xsd:language:diplomasupplement", name = "Underline", scope = RichTextTagType.class)
    public JAXBElement<String> createRichTextTagTypeUnderline(String value) {
        return new JAXBElement<String>(_RichTextTagTypeUnderline_QNAME, String.class, RichTextTagType.class, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:crue:academic:xsd:language:diplomasupplement", name = "Bold", scope = RichTextTagType.class)
    public JAXBElement<String> createRichTextTagTypeBold(String value) {
        return new JAXBElement<String>(_RichTextTagTypeBold_QNAME, String.class, RichTextTagType.class, value);
    }

}
