package ieci.tecdoc.sgm.tram.ws.server.sigem;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2020-12-11T18:50:19.420+01:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://server.ws.tram.sgm.tecdoc.ieci", name = "TramitacionWebService")
@XmlSeeAlso({ieci.tecdoc.sgm.tram.ws.server.dto.ObjectFactory.class, ieci.tecdoc.sgm.core.services.dto.ObjectFactory.class, ObjectFactory.class})
public interface TramitacionWebService {

    @WebMethod
    @RequestWrapper(localName = "getJustificanteFirma", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetJustificanteFirma")
    @ResponseWrapper(localName = "getJustificanteFirmaResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetJustificanteFirmaResponse")
    @WebResult(name = "getJustificanteFirmaReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Binario getJustificanteFirma(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "guid", targetNamespace = "")
        java.lang.String guid
    );

    @WebMethod
    @RequestWrapper(localName = "getProcedimientosPorTipo", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetProcedimientosPorTipo")
    @ResponseWrapper(localName = "getProcedimientosPorTipoResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetProcedimientosPorTipoResponse")
    @WebResult(name = "getProcedimientosPorTipoReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.ListaInfoBProcedimientos getProcedimientosPorTipo(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "tipoProc", targetNamespace = "")
        int tipoProc,
        @WebParam(name = "nombre", targetNamespace = "")
        java.lang.String nombre
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerRegistroEntidad", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.ObtenerRegistroEntidad")
    @ResponseWrapper(localName = "obtenerRegistroEntidadResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.ObtenerRegistroEntidadResponse")
    @WebResult(name = "obtenerRegistroEntidadReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Cadena obtenerRegistroEntidad(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "nombreEntidad", targetNamespace = "")
        java.lang.String nombreEntidad,
        @WebParam(name = "numExp", targetNamespace = "")
        java.lang.String numExp,
        @WebParam(name = "idRegistro", targetNamespace = "")
        int idRegistro
    );

    @WebMethod
    @RequestWrapper(localName = "anexarDocsTramite", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.AnexarDocsTramite")
    @ResponseWrapper(localName = "anexarDocsTramiteResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.AnexarDocsTramiteResponse")
    @WebResult(name = "anexarDocsTramiteReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Booleano anexarDocsTramite(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "numExp", targetNamespace = "")
        java.lang.String numExp,
        @WebParam(name = "idTramite", targetNamespace = "")
        int idTramite,
        @WebParam(name = "regNum", targetNamespace = "")
        java.lang.String regNum,
        @WebParam(name = "regDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar regDate,
        @WebParam(name = "documents", targetNamespace = "")
        java.util.List<ieci.tecdoc.sgm.tram.ws.server.dto.DocumentoExpediente> documents
    );

    @WebMethod
    @RequestWrapper(localName = "recibirDocumentoFirmado", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.RecibirDocumentoFirmado")
    @ResponseWrapper(localName = "recibirDocumentoFirmadoResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.RecibirDocumentoFirmadoResponse")
    @WebResult(name = "recibirDocumentoFirmadoReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Cadena recibirDocumentoFirmado(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "numExp", targetNamespace = "")
        java.lang.String numExp,
        @WebParam(name = "idDocumento", targetNamespace = "")
        java.lang.String idDocumento
    );

    @WebMethod
    @RequestWrapper(localName = "anularLicenciaRRHH", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.AnularLicenciaRRHH")
    @ResponseWrapper(localName = "anularLicenciaRRHHResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.AnularLicenciaRRHHResponse")
    @WebResult(name = "anularLicenciaRRHHReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Booleano anularLicenciaRRHH(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "numexp", targetNamespace = "")
        java.lang.String numexp
    );

    @WebMethod
    @RequestWrapper(localName = "establecerDatosRegistroEntidad", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.EstablecerDatosRegistroEntidad")
    @ResponseWrapper(localName = "establecerDatosRegistroEntidadResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.EstablecerDatosRegistroEntidadResponse")
    @WebResult(name = "establecerDatosRegistroEntidadReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Entero establecerDatosRegistroEntidad(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "nombreEntidad", targetNamespace = "")
        java.lang.String nombreEntidad,
        @WebParam(name = "numExp", targetNamespace = "")
        java.lang.String numExp,
        @WebParam(name = "xmlDatosEspecificos", targetNamespace = "")
        java.lang.String xmlDatosEspecificos
    );

    @WebMethod
    @RequestWrapper(localName = "busquedaAvanzada", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.BusquedaAvanzada")
    @ResponseWrapper(localName = "busquedaAvanzadaResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.BusquedaAvanzadaResponse")
    @WebResult(name = "busquedaAvanzadaReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Cadena busquedaAvanzada(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "nombreGrupo", targetNamespace = "")
        java.lang.String nombreGrupo,
        @WebParam(name = "nombreFrmBusqueda", targetNamespace = "")
        java.lang.String nombreFrmBusqueda,
        @WebParam(name = "xmlBusqueda", targetNamespace = "")
        java.lang.String xmlBusqueda,
        @WebParam(name = "dominio", targetNamespace = "")
        int dominio
    );

    @WebMethod
    @RequestWrapper(localName = "moverExpedienteAFase", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.MoverExpedienteAFase")
    @ResponseWrapper(localName = "moverExpedienteAFaseResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.MoverExpedienteAFaseResponse")
    @WebResult(name = "moverExpedienteAFaseReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Booleano moverExpedienteAFase(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "numExp", targetNamespace = "")
        java.lang.String numExp,
        @WebParam(name = "idFaseCatalogo", targetNamespace = "")
        java.lang.String idFaseCatalogo
    );

    @WebMethod
    @RequestWrapper(localName = "getFichero", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetFichero")
    @ResponseWrapper(localName = "getFicheroResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetFicheroResponse")
    @WebResult(name = "getFicheroReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Binario getFichero(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "guid", targetNamespace = "")
        java.lang.String guid
    );

    @WebMethod
    @RequestWrapper(localName = "getFicheroTemp", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetFicheroTemp")
    @ResponseWrapper(localName = "getFicheroTempResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetFicheroTempResponse")
    @WebResult(name = "getFicheroTempReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Binario getFicheroTemp(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "guid", targetNamespace = "")
        java.lang.String guid
    );

    @WebMethod
    @RequestWrapper(localName = "archivarExpedientes", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.ArchivarExpedientes")
    @ResponseWrapper(localName = "archivarExpedientesResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.ArchivarExpedientesResponse")
    @WebResult(name = "archivarExpedientesReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.core.services.dto.RetornoServicio archivarExpedientes(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "idExps", targetNamespace = "")
        java.util.List<java.lang.String> idExps
    );

    @WebMethod
    @RequestWrapper(localName = "getIdsExpedientes", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetIdsExpedientes")
    @ResponseWrapper(localName = "getIdsExpedientesResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetIdsExpedientesResponse")
    @WebResult(name = "getIdsExpedientesReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.ListaIdentificadores getIdsExpedientes(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "idProc", targetNamespace = "")
        java.lang.String idProc,
        @WebParam(name = "fechaIni", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar fechaIni,
        @WebParam(name = "fechaFin", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar fechaFin,
        @WebParam(name = "tipoOrd", targetNamespace = "")
        int tipoOrd
    );

    @WebMethod
    @RequestWrapper(localName = "getInfoOcupacion", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetInfoOcupacion")
    @ResponseWrapper(localName = "getInfoOcupacionResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetInfoOcupacionResponse")
    @WebResult(name = "getInfoOcupacionReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.InfoOcupacion getInfoOcupacion(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad
    );

    @WebMethod
    @RequestWrapper(localName = "getInfoFichero", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetInfoFichero")
    @ResponseWrapper(localName = "getInfoFicheroResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetInfoFicheroResponse")
    @WebResult(name = "getInfoFicheroReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.InfoFichero getInfoFichero(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "guid", targetNamespace = "")
        java.lang.String guid
    );

    @WebMethod
    @RequestWrapper(localName = "eliminaFicheros", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.EliminaFicheros")
    @ResponseWrapper(localName = "eliminaFicherosResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.EliminaFicherosResponse")
    @WebResult(name = "eliminaFicherosReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.core.services.dto.RetornoServicio eliminaFicheros(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "guids", targetNamespace = "")
        java.util.List<java.lang.String> guids
    );

    @WebMethod
    @RequestWrapper(localName = "getProcedimientos", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetProcedimientos")
    @ResponseWrapper(localName = "getProcedimientosResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetProcedimientosResponse")
    @WebResult(name = "getProcedimientosReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.ListaInfoBProcedimientos getProcedimientos(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "idProcs", targetNamespace = "")
        java.util.List<java.lang.String> idProcs
    );

    @WebMethod
    @RequestWrapper(localName = "setFicheroTemp", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.SetFicheroTemp")
    @ResponseWrapper(localName = "setFicheroTempResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.SetFicheroTempResponse")
    @WebResult(name = "setFicheroTempReturn", targetNamespace = "")
    public boolean setFicheroTemp(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "guid", targetNamespace = "")
        java.lang.String guid,
        @WebParam(name = "data", targetNamespace = "")
        byte[] data
    );

    @WebMethod
    @RequestWrapper(localName = "crearExpediente", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.CrearExpediente")
    @ResponseWrapper(localName = "crearExpedienteResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.CrearExpedienteResponse")
    @WebResult(name = "crearExpedienteReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Cadena crearExpediente(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "commonData", targetNamespace = "")
        ieci.tecdoc.sgm.tram.ws.server.dto.DatosComunesExpediente commonData,
        @WebParam(name = "specificDataXML", targetNamespace = "")
        java.lang.String specificDataXML,
        @WebParam(name = "documents", targetNamespace = "")
        java.util.List<ieci.tecdoc.sgm.tram.ws.server.dto.DocumentoExpediente> documents,
        @WebParam(name = "initSystem", targetNamespace = "")
        java.lang.String initSystem
    );

    @WebMethod
    @RequestWrapper(localName = "getProcedimiento", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetProcedimiento")
    @ResponseWrapper(localName = "getProcedimientoResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetProcedimientoResponse")
    @WebResult(name = "getProcedimientoReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Procedimiento getProcedimiento(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "idProc", targetNamespace = "")
        java.lang.String idProc
    );

    @WebMethod
    @RequestWrapper(localName = "cambiarEstadoAdministrativo", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.CambiarEstadoAdministrativo")
    @ResponseWrapper(localName = "cambiarEstadoAdministrativoResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.CambiarEstadoAdministrativoResponse")
    @WebResult(name = "cambiarEstadoAdministrativoReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Booleano cambiarEstadoAdministrativo(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "numExp", targetNamespace = "")
        java.lang.String numExp,
        @WebParam(name = "estadoAdm", targetNamespace = "")
        java.lang.String estadoAdm
    );

    @WebMethod
    @RequestWrapper(localName = "getExpediente", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetExpediente")
    @ResponseWrapper(localName = "getExpedienteResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetExpedienteResponse")
    @WebResult(name = "getExpedienteReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Expediente getExpediente(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "idExp", targetNamespace = "")
        java.lang.String idExp
    );

    @WebMethod
    @RequestWrapper(localName = "anexarDocsExpediente", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.AnexarDocsExpediente")
    @ResponseWrapper(localName = "anexarDocsExpedienteResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.AnexarDocsExpedienteResponse")
    @WebResult(name = "anexarDocsExpedienteReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Booleano anexarDocsExpediente(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "numExp", targetNamespace = "")
        java.lang.String numExp,
        @WebParam(name = "regNum", targetNamespace = "")
        java.lang.String regNum,
        @WebParam(name = "regDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar regDate,
        @WebParam(name = "documents", targetNamespace = "")
        java.util.List<ieci.tecdoc.sgm.tram.ws.server.dto.DocumentoExpediente> documents
    );

    @WebMethod
    @RequestWrapper(localName = "getExpedientes", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetExpedientes")
    @ResponseWrapper(localName = "getExpedientesResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.GetExpedientesResponse")
    @WebResult(name = "getExpedientesReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.ListaInfoBExpedientes getExpedientes(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "idExps", targetNamespace = "")
        java.util.List<java.lang.String> idExps
    );

    @WebMethod
    @RequestWrapper(localName = "iniciarExpediente", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.IniciarExpediente")
    @ResponseWrapper(localName = "iniciarExpedienteResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.IniciarExpedienteResponse")
    @WebResult(name = "iniciarExpedienteReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Booleano iniciarExpediente(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "commonData", targetNamespace = "")
        ieci.tecdoc.sgm.tram.ws.server.dto.DatosComunesExpediente commonData,
        @WebParam(name = "specificDataXML", targetNamespace = "")
        java.lang.String specificDataXML,
        @WebParam(name = "documents", targetNamespace = "")
        java.util.List<ieci.tecdoc.sgm.tram.ws.server.dto.DocumentoExpediente> documents
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerRegistrosEntidad", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.ObtenerRegistrosEntidad")
    @ResponseWrapper(localName = "obtenerRegistrosEntidadResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.ObtenerRegistrosEntidadResponse")
    @WebResult(name = "obtenerRegistrosEntidadReturn", targetNamespace = "")
    public ieci.tecdoc.sgm.tram.ws.server.dto.Cadena obtenerRegistrosEntidad(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "nombreEntidad", targetNamespace = "")
        java.lang.String nombreEntidad,
        @WebParam(name = "numExp", targetNamespace = "")
        java.lang.String numExp
    );

    @WebMethod
    @RequestWrapper(localName = "queryEntities", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.QueryEntities")
    @ResponseWrapper(localName = "queryEntitiesResponse", targetNamespace = "", className = "ieci.tecdoc.sgm.tram.ws.server.sigem.QueryEntitiesResponse")
    @WebResult(name = "queryEntitiesReturn", targetNamespace = "")
    public java.util.List<java.lang.String> queryEntities(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.String idEntidad,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "query", targetNamespace = "")
        java.lang.String query
    );
}
