//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.eu.stork.names.tc.stork._2_0.academic.generaldiploma;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for CourseUnitType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="CourseUnitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Code" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}PlainTextType" minOccurs="0"/>
 *         &lt;element name="ScientificArea" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}PlainTextType" minOccurs="0"/>
 *         &lt;element name="Title" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}PlainTextType"/>
 *         &lt;element name="Theme" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}PlainTextType" minOccurs="0"/>
 *         &lt;element name="Type" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma>PlainTextType">
 *                 &lt;attribute name="type" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}CourseUnitTypeType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="YearOfStudy" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma>PlainTextType">
 *                 &lt;attribute name="year" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}PositiveDecimalType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Level" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma>PlainTextType">
 *                 &lt;attribute name="eheaFramework" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}EHEAFrameworkType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ECTSCredits" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}PositiveDecimalType" minOccurs="0"/>
 *         &lt;element name="LocalCredits" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}PositiveDecimalType" minOccurs="0"/>
 *         &lt;element name="Hours" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}PositiveDecimalType" minOccurs="0"/>
 *         &lt;element name="LanguagesOfInstruction" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}CourseUnitLanguagesOfInstructionType" minOccurs="0"/>
 *         &lt;element name="ModeOfDelivery" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma>PlainTextType">
 *                 &lt;attribute name="modeOfDelivery" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}ModeOfDeliveryType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="WorkPlacements" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}CourseUnitWorkPlacementsType" minOccurs="0"/>
 *         &lt;element name="StudentPerformance" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}CourseUnitStudentPerformanceType" minOccurs="0"/>
 *         &lt;element name="NameOfLecturers" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType" minOccurs="0"/>
 *         &lt;element name="LearningOutcomes" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType" minOccurs="0"/>
 *         &lt;element name="PrerequisitesAndCorequisites" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType" minOccurs="0"/>
 *         &lt;element name="PrerequisitesScholarshipLevel" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType" minOccurs="0"/>
 *         &lt;element name="PrerequisitesOtherTitles" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType" minOccurs="0"/>
 *         &lt;element name="RecomendedOptionalProgrammeComponents" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType" minOccurs="0"/>
 *         &lt;element name="CourseContents" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType" minOccurs="0"/>
 *         &lt;element name="RecomendedOrRequiredReading" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType" minOccurs="0"/>
 *         &lt;element name="PlanedLearningActivitiesAndTeachingMethod" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType" minOccurs="0"/>
 *         &lt;element name="AssesmentMethodsAndCriteria" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType" minOccurs="0"/>
 *         &lt;element name="Observations" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="groupID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="institutionAdministeringStudiesID" type="{http://www.w3.org/2001/XMLSchema}string" default="DEF-IAS" />
 *       &lt;attribute name="isRequiredByTheProgramme" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CourseUnitType", propOrder = {
    "code",
    "scientificArea",
    "title",
    "theme",
    "type",
    "yearOfStudy",
    "level",
    "ectsCredits",
    "localCredits",
    "hours",
    "languagesOfInstruction",
    "modeOfDelivery",
    "workPlacements",
    "studentPerformance",
    "nameOfLecturers",
    "learningOutcomes",
    "prerequisitesAndCorequisites",
    "prerequisitesScholarshipLevel",
    "prerequisitesOtherTitles",
    "recomendedOptionalProgrammeComponents",
    "courseContents",
    "recomendedOrRequiredReading",
    "planedLearningActivitiesAndTeachingMethod",
    "assesmentMethodsAndCriteria",
    "observations"
})
public class CourseUnitType {

    @XmlElement(name = "Code")
    protected String code;
    @XmlElement(name = "ScientificArea")
    protected String scientificArea;
    @XmlElement(name = "Title", required = true)
    protected String title;
    @XmlElement(name = "Theme")
    protected String theme;
    @XmlElement(name = "Type")
    protected CourseUnitType.Type type;
    @XmlElement(name = "YearOfStudy")
    protected CourseUnitType.YearOfStudy yearOfStudy;
    @XmlElement(name = "Level")
    protected CourseUnitType.Level level;
    @XmlElement(name = "ECTSCredits")
    protected BigDecimal ectsCredits;
    @XmlElement(name = "LocalCredits")
    protected BigDecimal localCredits;
    @XmlElement(name = "Hours")
    protected BigDecimal hours;
    @XmlElement(name = "LanguagesOfInstruction")
    protected CourseUnitLanguagesOfInstructionType languagesOfInstruction;
    @XmlElement(name = "ModeOfDelivery")
    protected CourseUnitType.ModeOfDelivery modeOfDelivery;
    @XmlElement(name = "WorkPlacements")
    protected CourseUnitWorkPlacementsType workPlacements;
    @XmlElement(name = "StudentPerformance")
    protected CourseUnitStudentPerformanceType studentPerformance;
    @XmlElement(name = "NameOfLecturers")
    protected RichTextTagType nameOfLecturers;
    @XmlElement(name = "LearningOutcomes")
    protected RichTextTagType learningOutcomes;
    @XmlElement(name = "PrerequisitesAndCorequisites")
    protected RichTextTagType prerequisitesAndCorequisites;
    @XmlElement(name = "PrerequisitesScholarshipLevel")
    protected RichTextTagType prerequisitesScholarshipLevel;
    @XmlElement(name = "PrerequisitesOtherTitles")
    protected RichTextTagType prerequisitesOtherTitles;
    @XmlElement(name = "RecomendedOptionalProgrammeComponents")
    protected RichTextTagType recomendedOptionalProgrammeComponents;
    @XmlElement(name = "CourseContents")
    protected RichTextTagType courseContents;
    @XmlElement(name = "RecomendedOrRequiredReading")
    protected RichTextTagType recomendedOrRequiredReading;
    @XmlElement(name = "PlanedLearningActivitiesAndTeachingMethod")
    protected RichTextTagType planedLearningActivitiesAndTeachingMethod;
    @XmlElement(name = "AssesmentMethodsAndCriteria")
    protected RichTextTagType assesmentMethodsAndCriteria;
    @XmlElement(name = "Observations")
    protected RichTextTagType observations;
    @XmlAttribute(name = "groupID")
    protected String groupID;
    @XmlAttribute(name = "institutionAdministeringStudiesID")
    protected String institutionAdministeringStudiesID;
    @XmlAttribute(name = "isRequiredByTheProgramme")
    protected Boolean isRequiredByTheProgramme;

    /**
     * Gets the value of the code property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the scientificArea property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getScientificArea() {
        return scientificArea;
    }

    /**
     * Sets the value of the scientificArea property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setScientificArea(String value) {
        this.scientificArea = value;
    }

    /**
     * Gets the value of the title property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the theme property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTheme() {
        return theme;
    }

    /**
     * Sets the value of the theme property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTheme(String value) {
        this.theme = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link CourseUnitType.Type }
     *
     */
    public CourseUnitType.Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is {@link CourseUnitType.Type }
     *
     */
    public void setType(CourseUnitType.Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the yearOfStudy property.
     *
     * @return possible object is {@link CourseUnitType.YearOfStudy }
     *
     */
    public CourseUnitType.YearOfStudy getYearOfStudy() {
        return yearOfStudy;
    }

    /**
     * Sets the value of the yearOfStudy property.
     *
     * @param value allowed object is {@link CourseUnitType.YearOfStudy }
     *
     */
    public void setYearOfStudy(CourseUnitType.YearOfStudy value) {
        this.yearOfStudy = value;
    }

    /**
     * Gets the value of the level property.
     *
     * @return possible object is {@link CourseUnitType.Level }
     *
     */
    public CourseUnitType.Level getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     *
     * @param value allowed object is {@link CourseUnitType.Level }
     *
     */
    public void setLevel(CourseUnitType.Level value) {
        this.level = value;
    }

    /**
     * Gets the value of the ectsCredits property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getECTSCredits() {
        return ectsCredits;
    }

    /**
     * Sets the value of the ectsCredits property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setECTSCredits(BigDecimal value) {
        this.ectsCredits = value;
    }

    /**
     * Gets the value of the localCredits property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getLocalCredits() {
        return localCredits;
    }

    /**
     * Sets the value of the localCredits property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setLocalCredits(BigDecimal value) {
        this.localCredits = value;
    }

    /**
     * Gets the value of the hours property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getHours() {
        return hours;
    }

    /**
     * Sets the value of the hours property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setHours(BigDecimal value) {
        this.hours = value;
    }

    /**
     * Gets the value of the languagesOfInstruction property.
     *
     * @return possible object is {@link CourseUnitLanguagesOfInstructionType }
     *
     */
    public CourseUnitLanguagesOfInstructionType getLanguagesOfInstruction() {
        return languagesOfInstruction;
    }

    /**
     * Sets the value of the languagesOfInstruction property.
     *
     * @param value allowed object is
     *     {@link CourseUnitLanguagesOfInstructionType }
     *
     */
    public void setLanguagesOfInstruction(CourseUnitLanguagesOfInstructionType value) {
        this.languagesOfInstruction = value;
    }

    /**
     * Gets the value of the modeOfDelivery property.
     *
     * @return possible object is {@link CourseUnitType.ModeOfDelivery }
     *
     */
    public CourseUnitType.ModeOfDelivery getModeOfDelivery() {
        return modeOfDelivery;
    }

    /**
     * Sets the value of the modeOfDelivery property.
     *
     * @param value allowed object is {@link CourseUnitType.ModeOfDelivery }
     *
     */
    public void setModeOfDelivery(CourseUnitType.ModeOfDelivery value) {
        this.modeOfDelivery = value;
    }

    /**
     * Gets the value of the workPlacements property.
     *
     * @return possible object is {@link CourseUnitWorkPlacementsType }
     *
     */
    public CourseUnitWorkPlacementsType getWorkPlacements() {
        return workPlacements;
    }

    /**
     * Sets the value of the workPlacements property.
     *
     * @param value allowed object is {@link CourseUnitWorkPlacementsType }
     *
     */
    public void setWorkPlacements(CourseUnitWorkPlacementsType value) {
        this.workPlacements = value;
    }

    /**
     * Gets the value of the studentPerformance property.
     *
     * @return possible object is {@link CourseUnitStudentPerformanceType }
     *
     */
    public CourseUnitStudentPerformanceType getStudentPerformance() {
        return studentPerformance;
    }

    /**
     * Sets the value of the studentPerformance property.
     *
     * @param value allowed object is {@link CourseUnitStudentPerformanceType }
     *
     */
    public void setStudentPerformance(CourseUnitStudentPerformanceType value) {
        this.studentPerformance = value;
    }

    /**
     * Gets the value of the nameOfLecturers property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getNameOfLecturers() {
        return nameOfLecturers;
    }

    /**
     * Sets the value of the nameOfLecturers property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setNameOfLecturers(RichTextTagType value) {
        this.nameOfLecturers = value;
    }

    /**
     * Gets the value of the learningOutcomes property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getLearningOutcomes() {
        return learningOutcomes;
    }

    /**
     * Sets the value of the learningOutcomes property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setLearningOutcomes(RichTextTagType value) {
        this.learningOutcomes = value;
    }

    /**
     * Gets the value of the prerequisitesAndCorequisites property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getPrerequisitesAndCorequisites() {
        return prerequisitesAndCorequisites;
    }

    /**
     * Sets the value of the prerequisitesAndCorequisites property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setPrerequisitesAndCorequisites(RichTextTagType value) {
        this.prerequisitesAndCorequisites = value;
    }

    /**
     * Gets the value of the prerequisitesScholarshipLevel property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getPrerequisitesScholarshipLevel() {
        return prerequisitesScholarshipLevel;
    }

    /**
     * Sets the value of the prerequisitesScholarshipLevel property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setPrerequisitesScholarshipLevel(RichTextTagType value) {
        this.prerequisitesScholarshipLevel = value;
    }

    /**
     * Gets the value of the prerequisitesOtherTitles property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getPrerequisitesOtherTitles() {
        return prerequisitesOtherTitles;
    }

    /**
     * Sets the value of the prerequisitesOtherTitles property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setPrerequisitesOtherTitles(RichTextTagType value) {
        this.prerequisitesOtherTitles = value;
    }

    /**
     * Gets the value of the recomendedOptionalProgrammeComponents property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getRecomendedOptionalProgrammeComponents() {
        return recomendedOptionalProgrammeComponents;
    }

    /**
     * Sets the value of the recomendedOptionalProgrammeComponents property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setRecomendedOptionalProgrammeComponents(RichTextTagType value) {
        this.recomendedOptionalProgrammeComponents = value;
    }

    /**
     * Gets the value of the courseContents property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getCourseContents() {
        return courseContents;
    }

    /**
     * Sets the value of the courseContents property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setCourseContents(RichTextTagType value) {
        this.courseContents = value;
    }

    /**
     * Gets the value of the recomendedOrRequiredReading property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getRecomendedOrRequiredReading() {
        return recomendedOrRequiredReading;
    }

    /**
     * Sets the value of the recomendedOrRequiredReading property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setRecomendedOrRequiredReading(RichTextTagType value) {
        this.recomendedOrRequiredReading = value;
    }

    /**
     * Gets the value of the planedLearningActivitiesAndTeachingMethod property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getPlanedLearningActivitiesAndTeachingMethod() {
        return planedLearningActivitiesAndTeachingMethod;
    }

    /**
     * Sets the value of the planedLearningActivitiesAndTeachingMethod property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setPlanedLearningActivitiesAndTeachingMethod(RichTextTagType value) {
        this.planedLearningActivitiesAndTeachingMethod = value;
    }

    /**
     * Gets the value of the assesmentMethodsAndCriteria property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getAssesmentMethodsAndCriteria() {
        return assesmentMethodsAndCriteria;
    }

    /**
     * Sets the value of the assesmentMethodsAndCriteria property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setAssesmentMethodsAndCriteria(RichTextTagType value) {
        this.assesmentMethodsAndCriteria = value;
    }

    /**
     * Gets the value of the observations property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getObservations() {
        return observations;
    }

    /**
     * Sets the value of the observations property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setObservations(RichTextTagType value) {
        this.observations = value;
    }

    /**
     * Gets the value of the groupID property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setGroupID(String value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the institutionAdministeringStudiesID property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getInstitutionAdministeringStudiesID() {
        if (institutionAdministeringStudiesID == null) {
            return "DEF-IAS";
        } else {
            return institutionAdministeringStudiesID;
        }
    }

    /**
     * Sets the value of the institutionAdministeringStudiesID property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setInstitutionAdministeringStudiesID(String value) {
        this.institutionAdministeringStudiesID = value;
    }

    /**
     * Gets the value of the isRequiredByTheProgramme property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public boolean isIsRequiredByTheProgramme() {
        if (isRequiredByTheProgramme == null) {
            return true;
        } else {
            return isRequiredByTheProgramme;
        }
    }

    /**
     * Sets the value of the isRequiredByTheProgramme property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setIsRequiredByTheProgramme(Boolean value) {
        this.isRequiredByTheProgramme = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma>PlainTextType">
     *       &lt;attribute name="eheaFramework" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}EHEAFrameworkType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Level {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "eheaFramework")
        protected EHEAFrameworkType eheaFramework;

        /**
         * Gets the value of the value property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the eheaFramework property.
         *
         * @return possible object is {@link EHEAFrameworkType }
         *
         */
        public EHEAFrameworkType getEheaFramework() {
            return eheaFramework;
        }

        /**
         * Sets the value of the eheaFramework property.
         *
         * @param value allowed object is {@link EHEAFrameworkType }
         *
         */
        public void setEheaFramework(EHEAFrameworkType value) {
            this.eheaFramework = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma>PlainTextType">
     *       &lt;attribute name="modeOfDelivery" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}ModeOfDeliveryType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ModeOfDelivery {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "modeOfDelivery")
        protected ModeOfDeliveryType modeOfDelivery;

        /**
         * Gets the value of the value property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the modeOfDelivery property.
         *
         * @return possible object is {@link ModeOfDeliveryType }
         *
         */
        public ModeOfDeliveryType getModeOfDelivery() {
            return modeOfDelivery;
        }

        /**
         * Sets the value of the modeOfDelivery property.
         *
         * @param value allowed object is {@link ModeOfDeliveryType }
         *
         */
        public void setModeOfDelivery(ModeOfDeliveryType value) {
            this.modeOfDelivery = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma>PlainTextType">
     *       &lt;attribute name="type" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}CourseUnitTypeType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Type {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "type")
        protected CourseUnitTypeType type;

        /**
         * Gets the value of the value property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the type property.
         *
         * @return possible object is {@link CourseUnitTypeType }
         *
         */
        public CourseUnitTypeType getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         *
         * @param value allowed object is {@link CourseUnitTypeType }
         *
         */
        public void setType(CourseUnitTypeType value) {
            this.type = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma>PlainTextType">
     *       &lt;attribute name="year" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}PositiveDecimalType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class YearOfStudy {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "year")
        protected BigDecimal year;

        /**
         * Gets the value of the value property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the year property.
         *
         * @return possible object is {@link BigDecimal }
         *
         */
        public BigDecimal getYear() {
            return year;
        }

        /**
         * Sets the value of the year property.
         *
         * @param value allowed object is {@link BigDecimal }
         *
         */
        public void setYear(BigDecimal value) {
            this.year = value;
        }

    }

}
