//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.eu.stork.names.tc.stork._2_0.academic.generaldiploma;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CourseUnitStudentPerformanceType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="CourseUnitStudentPerformanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LocalGrade" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}LocalGradeType"/>
 *         &lt;element name="ECTSGrade" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}ECTSGradingScaleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CourseUnitStudentPerformanceType", propOrder = {
    "localGrade",
    "ectsGrade"
})
public class CourseUnitStudentPerformanceType {

    @XmlElement(name = "LocalGrade", required = true)
    protected LocalGradeType localGrade;
    @XmlElement(name = "ECTSGrade")
    protected ECTSGradingScaleType ectsGrade;

    /**
     * Gets the value of the localGrade property.
     *
     * @return possible object is {@link LocalGradeType }
     *
     */
    public LocalGradeType getLocalGrade() {
        return localGrade;
    }

    /**
     * Sets the value of the localGrade property.
     *
     * @param value allowed object is {@link LocalGradeType }
     *
     */
    public void setLocalGrade(LocalGradeType value) {
        this.localGrade = value;
    }

    /**
     * Gets the value of the ectsGrade property.
     *
     * @return possible object is {@link ECTSGradingScaleType }
     *
     */
    public ECTSGradingScaleType getECTSGrade() {
        return ectsGrade;
    }

    /**
     * Sets the value of the ectsGrade property.
     *
     * @param value allowed object is {@link ECTSGradingScaleType }
     *
     */
    public void setECTSGrade(ECTSGradingScaleType value) {
        this.ectsGrade = value;
    }

}
