//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.eu.stork.names.tc.stork._2_0.academic.generaldiploma;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for CourseUnitWorkPlacementType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="CourseUnitWorkPlacementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CollaboratingInstitution" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}PlainTextType"/>
 *         &lt;element name="DateFrom" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}DateType" minOccurs="0"/>
 *         &lt;element name="DateTo" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}DateType" minOccurs="0"/>
 *         &lt;element name="TrainingHours" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}PositiveDecimalType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CourseUnitWorkPlacementType", propOrder = {
    "collaboratingInstitution",
    "dateFrom",
    "dateTo",
    "trainingHours"
})
public class CourseUnitWorkPlacementType {

    @XmlElement(name = "CollaboratingInstitution", required = true)
    protected String collaboratingInstitution;
    @XmlElement(name = "DateFrom")
    protected XMLGregorianCalendar dateFrom;
    @XmlElement(name = "DateTo")
    protected XMLGregorianCalendar dateTo;
    @XmlElement(name = "TrainingHours")
    protected BigDecimal trainingHours;

    /**
     * Gets the value of the collaboratingInstitution property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCollaboratingInstitution() {
        return collaboratingInstitution;
    }

    /**
     * Sets the value of the collaboratingInstitution property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCollaboratingInstitution(String value) {
        this.collaboratingInstitution = value;
    }

    /**
     * Gets the value of the dateFrom property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateFrom() {
        return dateFrom;
    }

    /**
     * Sets the value of the dateFrom property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setDateFrom(XMLGregorianCalendar value) {
        this.dateFrom = value;
    }

    /**
     * Gets the value of the dateTo property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateTo() {
        return dateTo;
    }

    /**
     * Sets the value of the dateTo property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setDateTo(XMLGregorianCalendar value) {
        this.dateTo = value;
    }

    /**
     * Gets the value of the trainingHours property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getTrainingHours() {
        return trainingHours;
    }

    /**
     * Sets the value of the trainingHours property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setTrainingHours(BigDecimal value) {
        this.trainingHours = value;
    }

}
