//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.eu.stork.names.tc.stork._2_0.academic.generaldiploma;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ECTSGradingScaleType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * <
 * pre>
 * &lt;simpleType name="ECTSGradingScaleType"> &lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"> &lt;enumeration value="A"/>
 * &lt;enumeration value="B"/> &lt;enumeration value="C"/> &lt;enumeration
 * value="D"/> &lt;enumeration value="E"/> &lt;enumeration value="FX"/>
 * &lt;enumeration value="F"/> &lt;/restriction> &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "ECTSGradingScaleType")
@XmlEnum
public enum ECTSGradingScaleType {

    A,
    B,
    C,
    D,
    E,
    FX,
    F;

    public String value() {
        return name();
    }

    public static ECTSGradingScaleType fromValue(String v) {
        return valueOf(v);
    }

}
