//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.eu.stork.names.tc.stork._2_0.academic.generaldiploma;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for GradingSchemeAndGradeDistributionGuidanceType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="GradingSchemeAndGradeDistributionGuidanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GradingScheme" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType"/>
 *         &lt;element name="GradeDistributionGuidance" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GradingSchemeAndGradeDistributionGuidanceType", propOrder = {
    "gradingScheme",
    "gradeDistributionGuidance"
})
public class GradingSchemeAndGradeDistributionGuidanceType {

    @XmlElement(name = "GradingScheme", required = true)
    protected RichTextTagType gradingScheme;
    @XmlElement(name = "GradeDistributionGuidance")
    protected RichTextTagType gradeDistributionGuidance;

    /**
     * Gets the value of the gradingScheme property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getGradingScheme() {
        return gradingScheme;
    }

    /**
     * Sets the value of the gradingScheme property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setGradingScheme(RichTextTagType value) {
        this.gradingScheme = value;
    }

    /**
     * Gets the value of the gradeDistributionGuidance property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getGradeDistributionGuidance() {
        return gradeDistributionGuidance;
    }

    /**
     * Sets the value of the gradeDistributionGuidance property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setGradeDistributionGuidance(RichTextTagType value) {
        this.gradeDistributionGuidance = value;
    }

}
