//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.eu.stork.names.tc.stork._2_0.academic.generaldiploma;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for InformationIdentifyingTheQualificationType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="InformationIdentifyingTheQualificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Qualification" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}QualificationType"/>
 *         &lt;element name="TitleConferred" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}TitleConferredType" minOccurs="0"/>
 *         &lt;element name="MainFieldsOfStudy" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType" minOccurs="0"/>
 *         &lt;element name="NameAndStatusOfAwardingInstitution" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}NameAndStatusOfAwardingInstitutionType"/>
 *         &lt;element name="NameAndStatusOfInstitutionAdministeringStudies" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}NameAndStatusOfInstitutionAdministeringStudiesType"/>
 *         &lt;element name="LanguagesOfInstructionAndExamination" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}LanguagesOfInstructionAndExaminationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InformationIdentifyingTheQualificationType", propOrder = {
    "qualification",
    "titleConferred",
    "mainFieldsOfStudy",
    "nameAndStatusOfAwardingInstitution",
    "nameAndStatusOfInstitutionAdministeringStudies",
    "languagesOfInstructionAndExamination"
})
public class InformationIdentifyingTheQualificationType {

    @XmlElement(name = "Qualification", required = true)
    protected QualificationType qualification;
    @XmlElement(name = "TitleConferred")
    protected TitleConferredType titleConferred;
    @XmlElement(name = "MainFieldsOfStudy")
    protected RichTextTagType mainFieldsOfStudy;
    @XmlElement(name = "NameAndStatusOfAwardingInstitution", required = true)
    protected NameAndStatusOfAwardingInstitutionType nameAndStatusOfAwardingInstitution;
    @XmlElement(name = "NameAndStatusOfInstitutionAdministeringStudies", required = true)
    protected NameAndStatusOfInstitutionAdministeringStudiesType nameAndStatusOfInstitutionAdministeringStudies;
    @XmlElement(name = "LanguagesOfInstructionAndExamination")
    protected LanguagesOfInstructionAndExaminationType languagesOfInstructionAndExamination;

    /**
     * Gets the value of the qualification property.
     *
     * @return possible object is {@link QualificationType }
     *
     */
    public QualificationType getQualification() {
        return qualification;
    }

    /**
     * Sets the value of the qualification property.
     *
     * @param value allowed object is {@link QualificationType }
     *
     */
    public void setQualification(QualificationType value) {
        this.qualification = value;
    }

    /**
     * Gets the value of the titleConferred property.
     *
     * @return possible object is {@link TitleConferredType }
     *
     */
    public TitleConferredType getTitleConferred() {
        return titleConferred;
    }

    /**
     * Sets the value of the titleConferred property.
     *
     * @param value allowed object is {@link TitleConferredType }
     *
     */
    public void setTitleConferred(TitleConferredType value) {
        this.titleConferred = value;
    }

    /**
     * Gets the value of the mainFieldsOfStudy property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getMainFieldsOfStudy() {
        return mainFieldsOfStudy;
    }

    /**
     * Sets the value of the mainFieldsOfStudy property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setMainFieldsOfStudy(RichTextTagType value) {
        this.mainFieldsOfStudy = value;
    }

    /**
     * Gets the value of the nameAndStatusOfAwardingInstitution property.
     *
     * @return possible object is
     *     {@link NameAndStatusOfAwardingInstitutionType }
     *
     */
    public NameAndStatusOfAwardingInstitutionType getNameAndStatusOfAwardingInstitution() {
        return nameAndStatusOfAwardingInstitution;
    }

    /**
     * Sets the value of the nameAndStatusOfAwardingInstitution property.
     *
     * @param value allowed object is
     *     {@link NameAndStatusOfAwardingInstitutionType }
     *
     */
    public void setNameAndStatusOfAwardingInstitution(NameAndStatusOfAwardingInstitutionType value) {
        this.nameAndStatusOfAwardingInstitution = value;
    }

    /**
     * Gets the value of the nameAndStatusOfInstitutionAdministeringStudies
     * property.
     *
     * @return possible object is
     *     {@link NameAndStatusOfInstitutionAdministeringStudiesType }
     *
     */
    public NameAndStatusOfInstitutionAdministeringStudiesType getNameAndStatusOfInstitutionAdministeringStudies() {
        return nameAndStatusOfInstitutionAdministeringStudies;
    }

    /**
     * Sets the value of the nameAndStatusOfInstitutionAdministeringStudies
     * property.
     *
     * @param value allowed object is
     *     {@link NameAndStatusOfInstitutionAdministeringStudiesType }
     *
     */
    public void setNameAndStatusOfInstitutionAdministeringStudies(NameAndStatusOfInstitutionAdministeringStudiesType value) {
        this.nameAndStatusOfInstitutionAdministeringStudies = value;
    }

    /**
     * Gets the value of the languagesOfInstructionAndExamination property.
     *
     * @return possible object is
     *     {@link LanguagesOfInstructionAndExaminationType }
     *
     */
    public LanguagesOfInstructionAndExaminationType getLanguagesOfInstructionAndExamination() {
        return languagesOfInstructionAndExamination;
    }

    /**
     * Sets the value of the languagesOfInstructionAndExamination property.
     *
     * @param value allowed object is
     *     {@link LanguagesOfInstructionAndExaminationType }
     *
     */
    public void setLanguagesOfInstructionAndExamination(LanguagesOfInstructionAndExaminationType value) {
        this.languagesOfInstructionAndExamination = value;
    }

}
