//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.eu.stork.names.tc.stork._2_0.academic.generaldiploma;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for InformationOnTheContentsAndResultsGainedType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="InformationOnTheContentsAndResultsGainedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ModeOfStudy" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType">
 *                 &lt;attribute name="modeOfStudy" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}ModeOfStudyType" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ProgrammeRequirements" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}ProgrammeRequirementsType" minOccurs="0"/>
 *         &lt;element name="ProgrammeDetails" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}ProgrammeDetailsType" minOccurs="0"/>
 *         &lt;element name="GradingSchemeAndGradeDistributionGuidance" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}GradingSchemeAndGradeDistributionGuidanceType" minOccurs="0"/>
 *         &lt;element name="OverallClassificationOfTheQualification" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InformationOnTheContentsAndResultsGainedType", propOrder = {
    "modeOfStudy",
    "programmeRequirements",
    "programmeDetails",
    "gradingSchemeAndGradeDistributionGuidance",
    "overallClassificationOfTheQualification"
})
public class InformationOnTheContentsAndResultsGainedType {

    @XmlElement(name = "ModeOfStudy")
    protected InformationOnTheContentsAndResultsGainedType.ModeOfStudy modeOfStudy;
    @XmlElement(name = "ProgrammeRequirements")
    protected ProgrammeRequirementsType programmeRequirements;
    @XmlElement(name = "ProgrammeDetails")
    protected ProgrammeDetailsType programmeDetails;
    @XmlElement(name = "GradingSchemeAndGradeDistributionGuidance")
    protected GradingSchemeAndGradeDistributionGuidanceType gradingSchemeAndGradeDistributionGuidance;
    @XmlElement(name = "OverallClassificationOfTheQualification")
    protected RichTextTagType overallClassificationOfTheQualification;

    /**
     * Gets the value of the modeOfStudy property.
     *
     * @return possible object is
     *     {@link InformationOnTheContentsAndResultsGainedType.ModeOfStudy }
     *
     */
    public InformationOnTheContentsAndResultsGainedType.ModeOfStudy getModeOfStudy() {
        return modeOfStudy;
    }

    /**
     * Sets the value of the modeOfStudy property.
     *
     * @param value allowed object is
     *     {@link InformationOnTheContentsAndResultsGainedType.ModeOfStudy }
     *
     */
    public void setModeOfStudy(InformationOnTheContentsAndResultsGainedType.ModeOfStudy value) {
        this.modeOfStudy = value;
    }

    /**
     * Gets the value of the programmeRequirements property.
     *
     * @return possible object is {@link ProgrammeRequirementsType }
     *
     */
    public ProgrammeRequirementsType getProgrammeRequirements() {
        return programmeRequirements;
    }

    /**
     * Sets the value of the programmeRequirements property.
     *
     * @param value allowed object is {@link ProgrammeRequirementsType }
     *
     */
    public void setProgrammeRequirements(ProgrammeRequirementsType value) {
        this.programmeRequirements = value;
    }

    /**
     * Gets the value of the programmeDetails property.
     *
     * @return possible object is {@link ProgrammeDetailsType }
     *
     */
    public ProgrammeDetailsType getProgrammeDetails() {
        return programmeDetails;
    }

    /**
     * Sets the value of the programmeDetails property.
     *
     * @param value allowed object is {@link ProgrammeDetailsType }
     *
     */
    public void setProgrammeDetails(ProgrammeDetailsType value) {
        this.programmeDetails = value;
    }

    /**
     * Gets the value of the gradingSchemeAndGradeDistributionGuidance property.
     *
     * @return possible object is
     *     {@link GradingSchemeAndGradeDistributionGuidanceType }
     *
     */
    public GradingSchemeAndGradeDistributionGuidanceType getGradingSchemeAndGradeDistributionGuidance() {
        return gradingSchemeAndGradeDistributionGuidance;
    }

    /**
     * Sets the value of the gradingSchemeAndGradeDistributionGuidance property.
     *
     * @param value allowed object is
     *     {@link GradingSchemeAndGradeDistributionGuidanceType }
     *
     */
    public void setGradingSchemeAndGradeDistributionGuidance(GradingSchemeAndGradeDistributionGuidanceType value) {
        this.gradingSchemeAndGradeDistributionGuidance = value;
    }

    /**
     * Gets the value of the overallClassificationOfTheQualification property.
     *
     * @return possible object is {@link RichTextTagType }
     *
     */
    public RichTextTagType getOverallClassificationOfTheQualification() {
        return overallClassificationOfTheQualification;
    }

    /**
     * Sets the value of the overallClassificationOfTheQualification property.
     *
     * @param value allowed object is {@link RichTextTagType }
     *
     */
    public void setOverallClassificationOfTheQualification(RichTextTagType value) {
        this.overallClassificationOfTheQualification = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType">
     *       &lt;attribute name="modeOfStudy" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}ModeOfStudyType" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ModeOfStudy
            extends RichTextTagType {

        @XmlAttribute(name = "modeOfStudy")
        protected ModeOfStudyType modeOfStudy;

        /**
         * Gets the value of the modeOfStudy property.
         *
         * @return possible object is {@link ModeOfStudyType }
         *
         */
        public ModeOfStudyType getModeOfStudy() {
            return modeOfStudy;
        }

        /**
         * Sets the value of the modeOfStudy property.
         *
         * @param value allowed object is {@link ModeOfStudyType }
         *
         */
        public void setModeOfStudy(ModeOfStudyType value) {
            this.modeOfStudy = value;
        }

    }

}
