//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.eu.stork.names.tc.stork._2_0.academic.generaldiploma;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for LanguagesOfInstructionAndExaminationType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="LanguagesOfInstructionAndExaminationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Language" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType">
 *                 &lt;attribute name="language" use="required" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}LanguageType" />
 *                 &lt;attribute name="percent" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}PercentType" />
 *                 &lt;attribute name="instruction" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                 &lt;attribute name="examination" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LanguagesOfInstructionAndExaminationType", propOrder = {
    "language"
})
public class LanguagesOfInstructionAndExaminationType {

    @XmlElement(name = "Language", required = true)
    protected List<LanguagesOfInstructionAndExaminationType.Language> language;

    /**
     * Gets the value of the language property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the language property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LanguagesOfInstructionAndExaminationType.Language }
     *
     *
     */
    public List<LanguagesOfInstructionAndExaminationType.Language> getLanguage() {
        if (language == null) {
            language = new ArrayList<LanguagesOfInstructionAndExaminationType.Language>();
        }
        return this.language;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}RichTextTagType">
     *       &lt;attribute name="language" use="required" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}LanguageType" />
     *       &lt;attribute name="percent" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}PercentType" />
     *       &lt;attribute name="instruction" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *       &lt;attribute name="examination" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Language
            extends RichTextTagType {

        @XmlAttribute(name = "language", required = true)
        protected LanguageType language;
        @XmlAttribute(name = "percent")
        protected BigDecimal percent;
        @XmlAttribute(name = "instruction")
        protected Boolean instruction;
        @XmlAttribute(name = "examination")
        protected Boolean examination;

        /**
         * Gets the value of the language property.
         *
         * @return possible object is {@link LanguageType }
         *
         */
        public LanguageType getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         *
         * @param value allowed object is {@link LanguageType }
         *
         */
        public void setLanguage(LanguageType value) {
            this.language = value;
        }

        /**
         * Gets the value of the percent property.
         *
         * @return possible object is {@link BigDecimal }
         *
         */
        public BigDecimal getPercent() {
            return percent;
        }

        /**
         * Sets the value of the percent property.
         *
         * @param value allowed object is {@link BigDecimal }
         *
         */
        public void setPercent(BigDecimal value) {
            this.percent = value;
        }

        /**
         * Gets the value of the instruction property.
         *
         * @return possible object is {@link Boolean }
         *
         */
        public boolean isInstruction() {
            if (instruction == null) {
                return true;
            } else {
                return instruction;
            }
        }

        /**
         * Sets the value of the instruction property.
         *
         * @param value allowed object is {@link Boolean }
         *
         */
        public void setInstruction(Boolean value) {
            this.instruction = value;
        }

        /**
         * Gets the value of the examination property.
         *
         * @return possible object is {@link Boolean }
         *
         */
        public Boolean isExamination() {
            return examination;
        }

        /**
         * Sets the value of the examination property.
         *
         * @param value allowed object is {@link Boolean }
         *
         */
        public void setExamination(Boolean value) {
            this.examination = value;
        }

    }

}
