//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 12:22:50 PM GMT 
//
package eu.stork.peps.complex.attributes.eu.stork.names.tc.stork._2_0.academic.generaldiploma;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for LocalGradeType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="LocalGradeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AcademicYear" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}AcademicYearType" minOccurs="0"/>
 *         &lt;element name="DateIssued" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}DateType" minOccurs="0"/>
 *         &lt;element name="Grade" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}PlainTextType"/>
 *         &lt;element name="Source" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma>PlainTextType">
 *                 &lt;attribute name="source" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}SourceGradeType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocalGradeType", propOrder = {
    "academicYear",
    "dateIssued",
    "grade",
    "source"
})
public class LocalGradeType {

    @XmlElement(name = "AcademicYear")
    protected String academicYear;
    @XmlElement(name = "DateIssued")
    protected XMLGregorianCalendar dateIssued;
    @XmlElement(name = "Grade", required = true)
    protected String grade;
    @XmlElement(name = "Source")
    protected LocalGradeType.Source source;

    /**
     * Gets the value of the academicYear property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAcademicYear() {
        return academicYear;
    }

    /**
     * Sets the value of the academicYear property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAcademicYear(String value) {
        this.academicYear = value;
    }

    /**
     * Gets the value of the dateIssued property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateIssued() {
        return dateIssued;
    }

    /**
     * Sets the value of the dateIssued property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setDateIssued(XMLGregorianCalendar value) {
        this.dateIssued = value;
    }

    /**
     * Gets the value of the grade property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGrade() {
        return grade;
    }

    /**
     * Sets the value of the grade property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setGrade(String value) {
        this.grade = value;
    }

    /**
     * Gets the value of the source property.
     *
     * @return possible object is {@link LocalGradeType.Source }
     *
     */
    public LocalGradeType.Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     *
     * @param value allowed object is {@link LocalGradeType.Source }
     *
     */
    public void setSource(LocalGradeType.Source value) {
        this.source = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma>PlainTextType">
     *       &lt;attribute name="source" type="{urn:eu:stork:names:tc:STORK:2.0:academic:generaldiploma}SourceGradeType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Source {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "source")
        protected SourceGradeType source;

        /**
         * Gets the value of the value property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the source property.
         *
         * @return possible object is {@link SourceGradeType }
         *
         */
        public SourceGradeType getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         *
         * @param value allowed object is {@link SourceGradeType }
         *
         */
        public void setSource(SourceGradeType value) {
            this.source = value;
        }

    }

}
