//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.25 at 10:59:25 AM CET 
//


package es.dipucr.jaxb.tribunalcuentas.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.dipucr.jaxb.tribunalcuentas.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.dipucr.jaxb.tribunalcuentas.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RelacionContratos.Contrato }
     * 
     */
    public RelacionContratos.Contrato createRelacionContratosContrato() {
        return new RelacionContratos.Contrato();
    }

    /**
     * Create an instance of {@link RelacionContratos.ContratoMenor.Publicidad.PublicidadLicitacion }
     * 
     */
    public RelacionContratos.ContratoMenor.Publicidad.PublicidadLicitacion createRelacionContratosContratoMenorPublicidadPublicidadLicitacion() {
        return new RelacionContratos.ContratoMenor.Publicidad.PublicidadLicitacion();
    }

    /**
     * Create an instance of {@link RelacionContratos.Contrato.Publicidad }
     * 
     */
    public RelacionContratos.Contrato.Publicidad createRelacionContratosContratoPublicidad() {
        return new RelacionContratos.Contrato.Publicidad();
    }

    /**
     * Create an instance of {@link RelacionContratos.Contrato.Lote }
     * 
     */
    public RelacionContratos.Contrato.Lote createRelacionContratosContratoLote() {
        return new RelacionContratos.Contrato.Lote();
    }

    /**
     * Create an instance of {@link RelacionContratos.Contrato.Publicidad.PublicidadFormalizacion }
     * 
     */
    public RelacionContratos.Contrato.Publicidad.PublicidadFormalizacion createRelacionContratosContratoPublicidadPublicidadFormalizacion() {
        return new RelacionContratos.Contrato.Publicidad.PublicidadFormalizacion();
    }

    /**
     * Create an instance of {@link RelacionContratos.Contrato.Publicidad.PublicidadAdjudicacion }
     * 
     */
    public RelacionContratos.Contrato.Publicidad.PublicidadAdjudicacion createRelacionContratosContratoPublicidadPublicidadAdjudicacion() {
        return new RelacionContratos.Contrato.Publicidad.PublicidadAdjudicacion();
    }

    /**
     * Create an instance of {@link RelacionContratos.Contrato.Contratista }
     * 
     */
    public RelacionContratos.Contrato.Contratista createRelacionContratosContratoContratista() {
        return new RelacionContratos.Contrato.Contratista();
    }

    /**
     * Create an instance of {@link RelacionContratos.Contrato.Publicidad.PublicidadLicitacion }
     * 
     */
    public RelacionContratos.Contrato.Publicidad.PublicidadLicitacion createRelacionContratosContratoPublicidadPublicidadLicitacion() {
        return new RelacionContratos.Contrato.Publicidad.PublicidadLicitacion();
    }

    /**
     * Create an instance of {@link RelacionContratos }
     * 
     */
    public RelacionContratos createRelacionContratos() {
        return new RelacionContratos();
    }

    /**
     * Create an instance of {@link RelacionContratos.ContratoMenor.Contratista }
     * 
     */
    public RelacionContratos.ContratoMenor.Contratista createRelacionContratosContratoMenorContratista() {
        return new RelacionContratos.ContratoMenor.Contratista();
    }

    /**
     * Create an instance of {@link RelacionContratos.Contrato.Modificacion }
     * 
     */
    public RelacionContratos.Contrato.Modificacion createRelacionContratosContratoModificacion() {
        return new RelacionContratos.Contrato.Modificacion();
    }

    /**
     * Create an instance of {@link RelacionContratos.ContratoMenor }
     * 
     */
    public RelacionContratos.ContratoMenor createRelacionContratosContratoMenor() {
        return new RelacionContratos.ContratoMenor();
    }

    /**
     * Create an instance of {@link RelacionContratos.ContratoMenor.Publicidad }
     * 
     */
    public RelacionContratos.ContratoMenor.Publicidad createRelacionContratosContratoMenorPublicidad() {
        return new RelacionContratos.ContratoMenor.Publicidad();
    }

}
