//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.11 at 10:06:22 AM CEST 
//


package es.dipucr.sigem.api.firma.xml.peticion;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.dipucr.firma.xml.peticion package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactoryFirmaLotesPeticion {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.dipucr.firma.xml.peticion
     * 
     */
    public ObjectFactoryFirmaLotesPeticion() {
    }

    /**
     * Create an instance of {@link Signbatch.Singlesign }
     * 
     */
    public Signbatch.Singlesign createSignbatchSinglesign() {
        return new Signbatch.Singlesign();
    }

    /**
     * Create an instance of {@link Signbatch }
     * 
     */
    public Signbatch createSignbatch() {
        return new Signbatch();
    }

    /**
     * Create an instance of {@link Signbatch.Singlesign.Signsaver }
     * 
     */
    public Signbatch.Singlesign.Signsaver createSignbatchSinglesignSignsaver() {
        return new Signbatch.Singlesign.Signsaver();
    }

}
