/* Copyright (C) 2012-13 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */

package es.seap.minhap.portafirmas.ws.mobile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import es.seap.minhap.portafirmas.ws.mobile.exception.MobileException;

/**
 * This class was generated by Apache CXF 2.3.0
 * Fri Jun 24 13:23:52 CEST 2016
 * Generated source version: 2.3.0
 * 
 */
 
@WebService(targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:v2.0", name = "MobileService")
public interface MobileService {

    @WebResult(name = "document", targetNamespace = "")
    @RequestWrapper(localName = "documentPreview", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.DocumentPreview")
    @WebMethod
    @ResponseWrapper(localName = "documentPreviewResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.DocumentPreviewResponse")
    public es.seap.minhap.portafirmas.ws.mobile.bean.MobileDocument documentPreview(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate,
        @WebParam(name = "documentId", targetNamespace = "")
        java.lang.String documentId
    ) throws MobileException;

    @WebResult(name = "requestList", targetNamespace = "")
    @RequestWrapper(localName = "queryRequestList", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.QueryRequestList")
    @WebMethod
    @ResponseWrapper(localName = "queryRequestListResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.QueryRequestListResponse")
    public es.seap.minhap.portafirmas.ws.mobile.bean.MobileRequestList queryRequestList(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate,
        @WebParam(name = "state", targetNamespace = "")
        java.lang.String state,
        @WebParam(name = "initPage", targetNamespace = "")
        java.lang.String initPage,
        @WebParam(name = "pageSize", targetNamespace = "")
        java.lang.String pageSize,
        @WebParam(name = "signFormats", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.mobile.bean.MobileStringList signFormats,
        @WebParam(name = "filters", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.mobile.bean.MobileRequestFilterList filters
    ) throws MobileException;

    @WebResult(name = "responseId", targetNamespace = "")
    @RequestWrapper(localName = "rejectRequest", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.RejectRequest")
    @WebMethod
    @ResponseWrapper(localName = "rejectRequestResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.RejectRequestResponse")
    public java.lang.String rejectRequest(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate,
        @WebParam(name = "requestId", targetNamespace = "")
        java.lang.String requestId,
        @WebParam(name = "textRejection", targetNamespace = "")
        java.lang.String textRejection
    ) throws MobileException;

    @WebResult(name = "document", targetNamespace = "")
    @RequestWrapper(localName = "reportPreview", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.ReportPreview")
    @WebMethod
    @ResponseWrapper(localName = "reportPreviewResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.ReportPreviewResponse")
    public es.seap.minhap.portafirmas.ws.mobile.bean.MobileDocument reportPreview(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate,
        @WebParam(name = "documentId", targetNamespace = "")
        java.lang.String documentId
    ) throws MobileException;

    @WebResult(name = "documentList", targetNamespace = "")
    @RequestWrapper(localName = "getDocumentsToSign", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.GetDocumentsToSign")
    @WebMethod
    @ResponseWrapper(localName = "getDocumentsToSignResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.GetDocumentsToSignResponse")
    public es.seap.minhap.portafirmas.ws.mobile.bean.MobileDocumentList getDocumentsToSign(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate,
        @WebParam(name = "requestTagId", targetNamespace = "")
        java.lang.String requestTagId
    ) throws MobileException;

    @WebResult(name = "document", targetNamespace = "")
    @RequestWrapper(localName = "signPreview", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.SignPreview")
    @WebMethod
    @ResponseWrapper(localName = "signPreviewResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.SignPreviewResponse")
    public es.seap.minhap.portafirmas.ws.mobile.bean.MobileDocument signPreview(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate,
        @WebParam(name = "documentId", targetNamespace = "")
        java.lang.String documentId
    ) throws MobileException;

    @WebResult(name = "applicationList", targetNamespace = "")
    @RequestWrapper(localName = "queryApplicationsMobile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.QueryApplicationsMobile")
    @WebMethod
    @ResponseWrapper(localName = "queryApplicationsMobileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.QueryApplicationsMobileResponse")
    public es.seap.minhap.portafirmas.ws.mobile.bean.MobileApplicationList queryApplicationsMobile(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate
    ) throws MobileException;

    @WebResult(name = "registerStatus", targetNamespace = "")
    @RequestWrapper(localName = "registerSIMUser", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.RegisterSIMUser")
    @WebMethod
    @ResponseWrapper(localName = "registerSIMUserResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.RegisterSIMUserResponse")
    public es.seap.minhap.portafirmas.ws.mobile.bean.MobileSIMUserStatus registerSIMUser(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate,
        @WebParam(name = "register", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.mobile.bean.MobileSIMUser register
    ) throws MobileException;

    @WebResult(name = "responseId", targetNamespace = "")
    @RequestWrapper(localName = "approveRequest", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.ApproveRequest")
    @WebMethod
    @ResponseWrapper(localName = "approveRequestResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.ApproveRequestResponse")
    public java.lang.String approveRequest(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate,
        @WebParam(name = "requestTagId", targetNamespace = "")
        java.lang.String requestTagId
    ) throws MobileException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "saveSign", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.SaveSign")
    @WebMethod
    @ResponseWrapper(localName = "saveSignResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.SaveSignResponse")
    public java.lang.String saveSign(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate,
        @WebParam(name = "requestTagId", targetNamespace = "")
        java.lang.String requestTagId,
        @WebParam(name = "docSignInfoList", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.mobile.bean.MobileDocSignInfoList docSignInfoList
    ) throws MobileException;

    @WebResult(name = "request", targetNamespace = "")
    @RequestWrapper(localName = "queryRequest", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.QueryRequest")
    @WebMethod
    @ResponseWrapper(localName = "queryRequestResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.QueryRequestResponse")
    public es.seap.minhap.portafirmas.ws.mobile.bean.MobileRequest queryRequest(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate,
        @WebParam(name = "requestId", targetNamespace = "")
        java.lang.String requestId
    ) throws MobileException;
    
    @WebResult(name = "nifCif", targetNamespace = "")
    @RequestWrapper(localName = "validateUser", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.ValidateUser")
    @WebMethod
    @ResponseWrapper(localName = "validateUserResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.ValidateUserResponse")
    public java.lang.String validateUser(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate
    ) throws MobileException;
    
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "updateNotifyPush", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.UpdateNotifyPush")
    @WebMethod
    @ResponseWrapper(localName = "updateNotifyPushResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.UpdateNotifyPushResponse")
    public java.lang.String updateNotifyPush(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate,
        @WebParam(name = "estadoNotifyPush", targetNamespace = "")
        java.lang.String estadoNotifyPush
    ) throws MobileException;
    
    @WebResult(name = "valorNotifyPush", targetNamespace = "")
    @RequestWrapper(localName = "estadoNotifyPush", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.EstadoNotifyPush")
    @WebMethod
    @ResponseWrapper(localName = "estadoNotifyPushResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.EstadoNotifyPushResponse")
    public java.lang.String estadoNotifyPush(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate
    ) throws MobileException;
    
    @WebResult(name = "solicitudAccesoClaveRespuesta", targetNamespace = "")
    @RequestWrapper(localName = "solicitudAccesoClave", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.SolicitudAccesoClave")
    @WebMethod
    @ResponseWrapper(localName = "solicitudAccesoClaveResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.SolicitudAccesoClaveResponse")
    public es.seap.minhap.portafirmas.ws.mobile.bean.MobileAccesoClave solicitudAccesoClave(
		@WebParam(name = "spUrl", targetNamespace = "")
        java.lang.String spUrl,
        @WebParam(name = "spReturn", targetNamespace = "")
        java.lang.String spReturn
    ) throws MobileException;

    @WebResult(name = "nifCif", targetNamespace = "")
    @RequestWrapper(localName = "procesarRespuestaClave", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.ProcesarRespuestaClave")
    @WebMethod
    @ResponseWrapper(localName = "procesarRespuestaClaveResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.ProcesarRespuestaClaveResponse")
    public java.lang.String procesarRespuestaClave(
        @WebParam(name = "samlresponse", targetNamespace = "")
        java.lang.String samlresponse,
        @WebParam(name = "remoteHost", targetNamespace = "")
        java.lang.String remoteHost
    ) throws MobileException;
    
    @WebResult(name = "fireTransactionResponse", targetNamespace = "")
    @RequestWrapper(localName = "fireTransaction", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.FireTransaction")
    @WebMethod
    @ResponseWrapper(localName = "fireTransactionResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.FireTransactionResponse")
    public es.seap.minhap.portafirmas.ws.mobile.bean.MobileFireTrasactionResponse fireTransaction(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate,
        @WebParam(name = "idRequestList", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.mobile.bean.MobileStringList idRequestList
    ) throws MobileException;

    @WebResult(name = "fireRequestList", targetNamespace = "")
    @RequestWrapper(localName = "signFireCloud", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.SignFireCloud")
    @WebMethod
    @ResponseWrapper(localName = "signFireCloudResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.seap.minhap.portafirmas.ws.mobile.request.SignFireCloudResponse")
    public es.seap.minhap.portafirmas.ws.mobile.bean.MobileFireRequestList signFireCloud(
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate,
        @WebParam(name = "idRequestList", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.mobile.bean.MobileStringList idRequestList,
        @WebParam(name = "transactionId", targetNamespace = "")
        java.lang.String transactionId
    ) throws MobileException;

    
}
