ALTER TABLE SPAC_DT_INTERVINIENTES ADD decreto_notificado varchar2(1);
ALTER TABLE SPAC_DT_INTERVINIENTES ADD decreto_trasladado varchar2(1);
ALTER TABLE SPAC_DT_INTERVINIENTES ADD acuse_generado varchar2(1);
ALTER TABLE SPAC_DT_INTERVINIENTES ADD recurso varchar2(16);
ALTER TABLE SPAC_DT_INTERVINIENTES ADD observaciones varchar2 (1000);
ALTER TABLE SPAC_DT_INTERVINIENTES ADD fecha_acuse timestamp;
ALTER TABLE SPAC_DT_INTERVINIENTES ADD motivo_acuse varchar2 (1000);
ALTER TABLE SPAC_DT_INTERVINIENTES ADD recurso_texto varchar2(1024);
ALTER TABLE SPAC_DT_INTERVINIENTES ADD asiste varchar2(2);
ALTER TABLE SPAC_DT_INTERVINIENTES ADD tipo_poder varchar2(25);
ALTER TABLE SPAC_DT_INTERVINIENTES ADD fecha_ini timestamp;
ALTER TABLE SPAC_DT_INTERVINIENTES ADD fecha_fin timestamp;
ALTER TABLE SPAC_DT_INTERVINIENTES ADD solicitar_oferta varchar2(2);
ALTER TABLE SPAC_DT_INTERVINIENTES ADD solicitada_oferta varchar2(2);
ALTER TABLE SPAC_DT_INTERVINIENTES ADD ccc varchar2 (1000);

DECLARE
dato clob;
begin
dato := '<entity version=''1.00''><editable>S</editable><dropable>N</dropable><status>0</status><fields><field id=''1''><physicalName>id_ext</physicalName><type>0</type><size>32</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''2''><physicalName>rol</physicalName><type>0</type><size>4</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''3''><physicalName>tipo</physicalName><type>3</type><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''4''><physicalName>tipo_persona</physicalName><type>0</type><size>1</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''5''><physicalName>ndoc</physicalName><type>0</type><size>12</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''6''><physicalName>nombre</physicalName><type>0</type><size>250</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''7''><physicalName>dirnot</physicalName><type>0</type><size>250</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''8''><physicalName>email</physicalName><type>0</type><size>250</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''9''><physicalName>c_postal</physicalName><type>0</type><size>10</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''10''><physicalName>localidad</physicalName><type>0</type><size>150</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''11''><physicalName>caut</physicalName><type>0</type><size>150</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''12''><physicalName>tfno_fijo</physicalName><type>0</type><size>32</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''13''><physicalName>tfno_movil</physicalName><type>0</type><size>32</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''14''><physicalName>tipo_direccion</physicalName><type>0</type><size>1</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''15''><physicalName>direcciontelematica</physicalName><type>0</type><size>60</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''16''><physicalName>id</physicalName><type>3</type><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''17''><physicalName>numexp</physicalName><type>0</type><size>30</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''18''><physicalName>iddireccionpostal</physicalName><type>0</type><size>32</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''19''><physicalName>DECRETO_NOTIFICADO</physicalName><descripcion><![CDATA[Decreto notificado]]></descripcion><type>0</type><size>1</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''20''><physicalName>DECRETO_TRASLADADO</physicalName><descripcion><![CDATA[Decreto Trasladado]]></descripcion><type>0</type><size>1</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''21''><physicalName>ACUSE_GENERADO</physicalName><descripcion><![CDATA[Acuse de recibo generado]]></descripcion><type>0</type><size>1</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''22''><physicalName>recurso</physicalName><descripcion><![CDATA[Recurso]]></descripcion><type>0</type><size>16</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''23''><physicalName>observaciones</physicalName><descripcion><![CDATA[Observaciones]]></descripcion><type>1</type><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''24''><physicalName>fecha_acuse</physicalName><descripcion><![CDATA[Fecha de acuse]]></descripcion><type>6</type><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''25''><physicalName>motivo_acuse</physicalName><descripcion><![CDATA[Motivo Acuse]]></descripcion><type>1</type><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''26''><physicalName>recurso_texto</physicalName><descripcion><![CDATA[Recurso texto]]></descripcion><type>0</type><size>1024</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''27''><physicalName>asiste</physicalName><type>0</type><size>2</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''28''><physicalName>tipo_poder</physicalName><descripcion><![CDATA[Tipo de Poder]]></descripcion><type>0</type><size>25</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''29''><physicalName>fecha_ini</physicalName><descripcion><![CDATA[Fecha de inicio de validez del Poder]]></descripcion><type>6</type><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''30''><physicalName>fecha_fin</physicalName><descripcion><![CDATA[Fecha de vencimiento del Poder]]></descripcion><type>6</type><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''31''><physicalName>solicitar_oferta</physicalName><descripcion><![CDATA[Solicitar oferta]]></descripcion><type>0</type><size>2</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''32''><physicalName>solicitada_oferta</physicalName><descripcion><![CDATA[Solicitada oferta]]></descripcion><type>0</type><size>2</size><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field><field id=''26''><physicalName>CCC</physicalName><descripcion><![CDATA[Cuenta bancaria]]></descripcion><type>1</type><nullable>S</nullable><documentarySearch>N</documentarySearch><multivalue>N</multivalue></field></fields><validations><validation id=''1''><fieldId>6</fieldId><table/><tableType/><class/><mandatory>S</mandatory><hierarchicalId/><hierarchicalName/></validation><validation id=''2''><fieldId>14</fieldId><table>SPAC_TBL_005</table><tableType>3</tableType><class/><mandatory>N</mandatory><hierarchicalId/><hierarchicalName/></validation><validation id=''3''><fieldId>2</fieldId><table>SPAC_TBL_002</table><tableType>3</tableType><class/><mandatory>N</mandatory><hierarchicalId/><hierarchicalName/></validation><validation id=''4''><fieldId>19</fieldId><table>SPAC_TBL_009</table><tableType>2</tableType><class/><mandatory>N</mandatory><hierarchicalId/><hierarchicalName/></validation><validation id=''6''><fieldId>22</fieldId><table>DPCR_RECURSOS</table><tableType>3</tableType><class/><mandatory>N</mandatory><hierarchicalId/><hierarchicalName/></validation><validation id=''7''><fieldId>28</fieldId><table>VLDTBL_TIPO_PODER</table><tableType>2</tableType><class/><mandatory>S</mandatory><hierarchicalId/><hierarchicalName/></validation></validations></entity>';
UPDATE SPAC_CT_ENTIDADES SET definicion=dato WHERE NOMBRE='SPAC_DT_INTERVINIENTES';
end;

DELETE FROM SPAC_CT_ENTIDADES_RESOURCES WHERE ID_ENT IN (SELECT ID FROM SPAC_CT_ENTIDADES WHERE NOMBRE='SPAC_DT_INTERVINIENTES');

INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','SPAC_DT_INTERVINIENTES','Participantes');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','LBL_VALIDADO','Validado');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','LBL_NO_VALIDADO','No Validado');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','NDOC','NIF/CIF');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','NOMBRE','Nombre');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','DIRNOT','Dirección Postal');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','LOCALIDAD','Ciudad');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','C_POSTAL','Código Postal');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','CAUT','Región/País');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','TFNO_FIJO','Tfno. Fijo');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','TFNO_MOVIL','Tfno. Móvil');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','DIRECCIONTELEMATICA','Dirección Telemática');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','TIPO_DIRECCION','Tipo Dirección Notificación');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','ROL','Relación');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','NUMDOCUMENTO','Nº Documento');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','LISTA','LISTADO DE PARTICIPANTES');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','IMAGEN','user');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','SPAC_DT_INTERVINIENTES_TAB_DATOS_PARTICIPANTE','Datos de Participante');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','ID_EXT','Referencia Externa');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','TIPO','Tipo');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','TIPO_PERSONA','Tipo de Persona');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','EMAIL','E-Mail');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','IDDIRECCIONPOSTAL','Id. de Dirección Postal');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','SEP_DIRECCIONES','DIRECCION NOTIFICACIÓN');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','LBL_CONFIRMADA','Verificada');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','LBL_LIBRE','Libre');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','TAB_REPRESENTANTE','Representante');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','TAB_REPRESENTANTE','Representante');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','TAB_REPRESENTANTE','Datos del Representante');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','DECRETO_NOTIFICADO','Decreto notificado');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','DECRETO_NOTIFICADO','Decreto notificado');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','DECRETO_NOTIFICADO','Decreto notificado');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','DECRETO_TRASLADADO','Decreto Trasladado');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','DECRETO_TRASLADADO','Decreto Trasladado');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','DECRETO_TRASLADADO','Decreto Trasladado');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','ACUSE_GENERADO','Acuse de recibo generado');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','ACUSE_GENERADO','Acuse de recibo generado');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','ACUSE_GENERADO','Acuse de recibo generado');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','RECURSO','Recurso');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','RECURSO','Recurso');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','RECURSO','Recurso');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','OBSERVACIONES','Observaciones');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','OBSERVACIONES','Observaciones');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','OBSERVACIONES','Observaciones');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','FECHA_ACUSE','Fecha Acuse');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','FECHA_ACUSE','Fecha Acuse');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','FECHA_ACUSE','Fecha Acuse');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','MOTIVO_ACUSE','Motivo acuse');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','MOTIVO_ACUSE','Motivo acuse');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','MOTIVO_ACUSE','Motivo acuse');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','RECURSO_TEXTO','Recurso texto');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','RECURSO_TEXTO','Recurso texto');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','RECURSO_TEXTO','Recurso texto');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','ASISTE','Asiste');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','ASISTE','Asiste');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','ASISTE','Asiste');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','TIPO_PODER','Tipo de Poder');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','TIPO_PODER','Tipo de Poder');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','TIPO_PODER','Tipo de Poder');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','FECHA_INI','Fecha de inicio');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','FECHA_INI','Fecha de inicio');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','FECHA_INI','Fecha de inicio');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','FECHA_FIN','Fecha de vencimiento');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','FECHA_FIN','Fecha de vencimiento');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','FECHA_FIN','Fecha de vencimiento');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','SOLICITAR_OFERTA','Solicitar oferta');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','SOLICITAR_OFERTA','Solicitar oferta');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','SOLICITAR_OFERTA','Solicitar oferta');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','SOLICITADA_OFERTA','Solicitada oferta');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','SOLICITADA_OFERTA','Solicitada oferta');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','SOLICITADA_OFERTA','Solicitada oferta');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','CCC','CC');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','CCC','CC');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','CCC','CC');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','es','HOLA','hola');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','gl','HOLA','hola');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','eu','HOLA','hola');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','TAB_REPRESENTANTE','Representante');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','DECRETO_NOTIFICADO','Decreto notificado');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','DECRETO_TRASLADADO','Decreto Trasladado');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','ACUSE_GENERADO','Acuse de recibo generado');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','RECURSO','Recurso');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','OBSERVACIONES','Observaciones');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','FECHA_ACUSE','Fecha Acuse');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','MOTIVO_ACUSE','Motivo acuse');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','RECURSO_TEXTO','Recurso texto');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','ASISTE','Asiste');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','TIPO_PODER','Tipo de Poder');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','FECHA_INI','Fecha de inicio');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','FECHA_FIN','Fecha de vencimiento');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','SOLICITAR_OFERTA','Solicitar oferta');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','SOLICITADA_OFERTA','Solicitada oferta');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','CCC','CC');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','_ca','HOLA','hola');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','CAUT','Regió/País');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','C_POSTAL','Codi Postal');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','DIRECCIONTELEMATICA','Adreça Telemàtica');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','DIRNOT','Adreça Postal');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','EMAIL','E-Mail');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','IDDIRECCIONPOSTAL','Id. de Adreça Postal');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','ID_EXT','Referència Externa');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','IMAGEN','user');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','LBL_CONFIRMADA','Verificada');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','LBL_LIBRE','Lliure');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','LBL_NO_VALIDADO','No Validat');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','LBL_VALIDADO','Validat');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','LISTA','LLISTAT DE PARTICIPANTS');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','LOCALIDAD','Ciutat');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','NDOC','NIF/CIF');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','NOMBRE','Nom');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','NUMDOCUMENTO','Nº Document');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','ROL','Relació');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','SEP_DIRECCIONES','ADREÇA NOTIFICACIÓ');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','SPAC_DT_INTERVINIENTES','Participants');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','SPAC_DT_INTERVINIENTES_TAB_DATOS_PARTICIPANTE','Dades de Participant');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','TFNO_FIJO','Tfn. Fix');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','TFNO_MOVIL','Tfno. Mòbil');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','TIPO','Tipus');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','TIPO_DIRECCION','Tipus Adreça Notificació');
INSERT INTO SPAC_CT_ENTIDADES_RESOURCES VALUES(SPAC_SQ_ID_ENTIDADESRESOURCES.NEXTVAL,'3','ca','TIPO_PERSONA','Tipus de Persona');