/* Copyright (C) 2012-13 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */

package es.seap.minhap.portafirmas.ws.eeutil.operfirma;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.0
 * Tue Feb 17 12:30:29 CET 2015
 * Generated source version: 2.3.0
 * 
 */
 
@WebService(targetNamespace = "http://service.ws.inside.dsic.mpt.es/", name = "EeUtilService")
@XmlSeeAlso({ObjectFactory.class})
public interface EeUtilService {

    @WebResult(name = "ResultadoValidacionInfo", targetNamespace = "")
    @RequestWrapper(localName = "validacionFirma", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.seap.minhap.portafirmas.ws.eeutil.operfirma.ValidacionFirma")
    @WebMethod(action = "urn:validacionFirma")
    @ResponseWrapper(localName = "validacionFirmaResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.seap.minhap.portafirmas.ws.eeutil.operfirma.ValidacionFirmaResponse")
    public es.seap.minhap.portafirmas.ws.eeutil.operfirma.ResultadoValidacionInfo validacionFirma(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.eeutil.operfirma.ApplicationLogin aplicacionInfo,
        @WebParam(name = "Firma", targetNamespace = "")
        byte[] firma,
        @WebParam(name = "TipoFirma", targetNamespace = "")
        java.lang.String tipoFirma,
        @WebParam(name = "DatosFirmados", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.eeutil.operfirma.DatosFirmados datosFirmados
    ) throws InSideException;

    @WebResult(name = "resultadoObtenerInformacionFirma", targetNamespace = "")
    @RequestWrapper(localName = "obtenerInformacionFirma", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.seap.minhap.portafirmas.ws.eeutil.operfirma.ObtenerInformacionFirma")
    @WebMethod(action = "urn:obtenerInformacionFirma")
    @ResponseWrapper(localName = "obtenerInformacionFirmaResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.seap.minhap.portafirmas.ws.eeutil.operfirma.ObtenerInformacionFirmaResponse")
    public es.seap.minhap.portafirmas.ws.eeutil.operfirma.InformacionFirma obtenerInformacionFirma(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.eeutil.operfirma.ApplicationLogin aplicacionInfo,
        @WebParam(name = "Firma", targetNamespace = "")
        byte[] firma,
        @WebParam(name = "opcionesObtenerInformacionFirma", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.eeutil.operfirma.OpcionesObtenerInformacionFirma opcionesObtenerInformacionFirma
    ) throws InSideException;

    @WebResult(name = "resultadoValidarCertificado", targetNamespace = "")
    @RequestWrapper(localName = "validarCertificado", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.seap.minhap.portafirmas.ws.eeutil.operfirma.ValidarCertificado")
    @WebMethod(action = "urn:validarCertificado")
    @ResponseWrapper(localName = "validarCertificadoResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.seap.minhap.portafirmas.ws.eeutil.operfirma.ValidarCertificadoResponse")
    public es.seap.minhap.portafirmas.ws.eeutil.operfirma.ResultadoValidarCertificado validarCertificado(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.eeutil.operfirma.ApplicationLogin aplicacionInfo,
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate
    ) throws InSideException;
    
    @WebResult(name = "resultadoGetInfoCertificado", targetNamespace = "")
    @RequestWrapper(localName = "getInfoCertificado", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.seap.minhap.portafirmas.ws.eeutil.operfirma.GetInfoCertificado")
    @WebMethod(action = "urn:getInfoCertificado")
    @ResponseWrapper(localName = "getInfoCertificadoResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.seap.minhap.portafirmas.ws.eeutil.operfirma.GetInfoCertificadoResponse")
    public es.seap.minhap.portafirmas.ws.eeutil.operfirma.InfoCertificado getInfoCertificado(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.eeutil.operfirma.ApplicationLogin aplicacionInfo,
        @WebParam(name = "certificate", targetNamespace = "")
        java.lang.String certificate
    ) throws InSideException;

    @WebResult(name = "ListaFirmantes", targetNamespace = "")
    @RequestWrapper(localName = "obtenerFirmantes", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.seap.minhap.portafirmas.ws.eeutil.operfirma.ObtenerFirmantes")
    @WebMethod(action = "urn:obtenerFirmantes")
    @ResponseWrapper(localName = "obtenerFirmantesResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.seap.minhap.portafirmas.ws.eeutil.operfirma.ObtenerFirmantesResponse")
    public es.seap.minhap.portafirmas.ws.eeutil.operfirma.ListaFirmaInfo obtenerFirmantes(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.eeutil.operfirma.ApplicationLogin aplicacionInfo,
        @WebParam(name = "Firma", targetNamespace = "")
        byte[] firma,
        @WebParam(name = "Datos", targetNamespace = "")
        byte[] datos,
        @WebParam(name = "TipoFirma", targetNamespace = "")
        java.lang.String tipoFirma
    ) throws InSideException;

    @WebResult(name = "resultadoAmpliarFirma", targetNamespace = "")
    @RequestWrapper(localName = "ampliarFirma", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.seap.minhap.portafirmas.ws.eeutil.operfirma.AmpliarFirma")
    @WebMethod(action = "urn:ampliarFirma")
    @ResponseWrapper(localName = "ampliarFirmaResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.seap.minhap.portafirmas.ws.eeutil.operfirma.AmpliarFirmaResponse")
    public es.seap.minhap.portafirmas.ws.eeutil.operfirma.ResultadoAmpliarFirma ampliarFirma(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.eeutil.operfirma.ApplicationLogin aplicacionInfo,
        @WebParam(name = "Firma", targetNamespace = "")
        byte[] firma,
        @WebParam(name = "configuracionAmpliarFirma", targetNamespace = "")
        es.seap.minhap.portafirmas.ws.eeutil.operfirma.ConfiguracionAmpliarFirma configuracionAmpliarFirma
    ) throws InSideException;
}
