/* Copyright (C) 2012-13 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */


package es.mpt.dsic.inside.ws.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import es.mpt.dsic.inside.ws.service.ApplicationLogin;
import es.mpt.dsic.inside.ws.service.DatosEntradaFichero;
import es.mpt.dsic.inside.ws.service.DatosSalida;
import es.mpt.dsic.inside.ws.service.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EeUtilFirmarService", targetNamespace = "http://service.ws.inside.dsic.mpt.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EeUtilFirmarService {


    /**
     * 
     * @param aplicacionInfo
     * @param datosEntrada
     * @return
     *     returns es.mpt.dsic.inside.ws.service.DatosSalida
     */
    @WebMethod(action = "urn:firmaFicheroWithPropertie")
    @WebResult(name = "datosSalida", targetNamespace = "")
    @RequestWrapper(localName = "firmaFicheroWithPropertie", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.inside.ws.service.FirmaFicheroWithPropertie")
    @ResponseWrapper(localName = "firmaFicheroWithPropertieResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.inside.ws.service.FirmaFicheroWithPropertieResponse")
    public DatosSalida firmaFicheroWithPropertie(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        ApplicationLogin aplicacionInfo,
        @WebParam(name = "datosEntrada", targetNamespace = "")
        DatosEntradaFichero datosEntrada);

    /**
     * 
     * @param aplicacionInfo
     * @param datosEntrada
     * @return
     *     returns es.mpt.dsic.inside.ws.service.DatosSalida
     */
    @WebMethod(action = "urn:FirmaFichero")
    @WebResult(name = "datosSalida", targetNamespace = "")
    @RequestWrapper(localName = "firmaFichero", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.inside.ws.service.FirmaFichero")
    @ResponseWrapper(localName = "firmaFicheroResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.inside.ws.service.FirmaFicheroResponse")
    public DatosSalida firmaFichero(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        ApplicationLogin aplicacionInfo,
        @WebParam(name = "datosEntrada", targetNamespace = "")
        DatosEntradaFichero datosEntrada);

}
